# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Fri Apr 17 21:17:06 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design KS128

create_clock -name "clk" -period 2.0 -waveform {0.0 1.0} 
set_load -pin_load 0.01 [get_ports {sum[127]}]
set_load -pin_load 0.01 [get_ports {sum[126]}]
set_load -pin_load 0.01 [get_ports {sum[125]}]
set_load -pin_load 0.01 [get_ports {sum[124]}]
set_load -pin_load 0.01 [get_ports {sum[123]}]
set_load -pin_load 0.01 [get_ports {sum[122]}]
set_load -pin_load 0.01 [get_ports {sum[121]}]
set_load -pin_load 0.01 [get_ports {sum[120]}]
set_load -pin_load 0.01 [get_ports {sum[119]}]
set_load -pin_load 0.01 [get_ports {sum[118]}]
set_load -pin_load 0.01 [get_ports {sum[117]}]
set_load -pin_load 0.01 [get_ports {sum[116]}]
set_load -pin_load 0.01 [get_ports {sum[115]}]
set_load -pin_load 0.01 [get_ports {sum[114]}]
set_load -pin_load 0.01 [get_ports {sum[113]}]
set_load -pin_load 0.01 [get_ports {sum[112]}]
set_load -pin_load 0.01 [get_ports {sum[111]}]
set_load -pin_load 0.01 [get_ports {sum[110]}]
set_load -pin_load 0.01 [get_ports {sum[109]}]
set_load -pin_load 0.01 [get_ports {sum[108]}]
set_load -pin_load 0.01 [get_ports {sum[107]}]
set_load -pin_load 0.01 [get_ports {sum[106]}]
set_load -pin_load 0.01 [get_ports {sum[105]}]
set_load -pin_load 0.01 [get_ports {sum[104]}]
set_load -pin_load 0.01 [get_ports {sum[103]}]
set_load -pin_load 0.01 [get_ports {sum[102]}]
set_load -pin_load 0.01 [get_ports {sum[101]}]
set_load -pin_load 0.01 [get_ports {sum[100]}]
set_load -pin_load 0.01 [get_ports {sum[99]}]
set_load -pin_load 0.01 [get_ports {sum[98]}]
set_load -pin_load 0.01 [get_ports {sum[97]}]
set_load -pin_load 0.01 [get_ports {sum[96]}]
set_load -pin_load 0.01 [get_ports {sum[95]}]
set_load -pin_load 0.01 [get_ports {sum[94]}]
set_load -pin_load 0.01 [get_ports {sum[93]}]
set_load -pin_load 0.01 [get_ports {sum[92]}]
set_load -pin_load 0.01 [get_ports {sum[91]}]
set_load -pin_load 0.01 [get_ports {sum[90]}]
set_load -pin_load 0.01 [get_ports {sum[89]}]
set_load -pin_load 0.01 [get_ports {sum[88]}]
set_load -pin_load 0.01 [get_ports {sum[87]}]
set_load -pin_load 0.01 [get_ports {sum[86]}]
set_load -pin_load 0.01 [get_ports {sum[85]}]
set_load -pin_load 0.01 [get_ports {sum[84]}]
set_load -pin_load 0.01 [get_ports {sum[83]}]
set_load -pin_load 0.01 [get_ports {sum[82]}]
set_load -pin_load 0.01 [get_ports {sum[81]}]
set_load -pin_load 0.01 [get_ports {sum[80]}]
set_load -pin_load 0.01 [get_ports {sum[79]}]
set_load -pin_load 0.01 [get_ports {sum[78]}]
set_load -pin_load 0.01 [get_ports {sum[77]}]
set_load -pin_load 0.01 [get_ports {sum[76]}]
set_load -pin_load 0.01 [get_ports {sum[75]}]
set_load -pin_load 0.01 [get_ports {sum[74]}]
set_load -pin_load 0.01 [get_ports {sum[73]}]
set_load -pin_load 0.01 [get_ports {sum[72]}]
set_load -pin_load 0.01 [get_ports {sum[71]}]
set_load -pin_load 0.01 [get_ports {sum[70]}]
set_load -pin_load 0.01 [get_ports {sum[69]}]
set_load -pin_load 0.01 [get_ports {sum[68]}]
set_load -pin_load 0.01 [get_ports {sum[67]}]
set_load -pin_load 0.01 [get_ports {sum[66]}]
set_load -pin_load 0.01 [get_ports {sum[65]}]
set_load -pin_load 0.01 [get_ports {sum[64]}]
set_load -pin_load 0.01 [get_ports {sum[63]}]
set_load -pin_load 0.01 [get_ports {sum[62]}]
set_load -pin_load 0.01 [get_ports {sum[61]}]
set_load -pin_load 0.01 [get_ports {sum[60]}]
set_load -pin_load 0.01 [get_ports {sum[59]}]
set_load -pin_load 0.01 [get_ports {sum[58]}]
set_load -pin_load 0.01 [get_ports {sum[57]}]
set_load -pin_load 0.01 [get_ports {sum[56]}]
set_load -pin_load 0.01 [get_ports {sum[55]}]
set_load -pin_load 0.01 [get_ports {sum[54]}]
set_load -pin_load 0.01 [get_ports {sum[53]}]
set_load -pin_load 0.01 [get_ports {sum[52]}]
set_load -pin_load 0.01 [get_ports {sum[51]}]
set_load -pin_load 0.01 [get_ports {sum[50]}]
set_load -pin_load 0.01 [get_ports {sum[49]}]
set_load -pin_load 0.01 [get_ports {sum[48]}]
set_load -pin_load 0.01 [get_ports {sum[47]}]
set_load -pin_load 0.01 [get_ports {sum[46]}]
set_load -pin_load 0.01 [get_ports {sum[45]}]
set_load -pin_load 0.01 [get_ports {sum[44]}]
set_load -pin_load 0.01 [get_ports {sum[43]}]
set_load -pin_load 0.01 [get_ports {sum[42]}]
set_load -pin_load 0.01 [get_ports {sum[41]}]
set_load -pin_load 0.01 [get_ports {sum[40]}]
set_load -pin_load 0.01 [get_ports {sum[39]}]
set_load -pin_load 0.01 [get_ports {sum[38]}]
set_load -pin_load 0.01 [get_ports {sum[37]}]
set_load -pin_load 0.01 [get_ports {sum[36]}]
set_load -pin_load 0.01 [get_ports {sum[35]}]
set_load -pin_load 0.01 [get_ports {sum[34]}]
set_load -pin_load 0.01 [get_ports {sum[33]}]
set_load -pin_load 0.01 [get_ports {sum[32]}]
set_load -pin_load 0.01 [get_ports {sum[31]}]
set_load -pin_load 0.01 [get_ports {sum[30]}]
set_load -pin_load 0.01 [get_ports {sum[29]}]
set_load -pin_load 0.01 [get_ports {sum[28]}]
set_load -pin_load 0.01 [get_ports {sum[27]}]
set_load -pin_load 0.01 [get_ports {sum[26]}]
set_load -pin_load 0.01 [get_ports {sum[25]}]
set_load -pin_load 0.01 [get_ports {sum[24]}]
set_load -pin_load 0.01 [get_ports {sum[23]}]
set_load -pin_load 0.01 [get_ports {sum[22]}]
set_load -pin_load 0.01 [get_ports {sum[21]}]
set_load -pin_load 0.01 [get_ports {sum[20]}]
set_load -pin_load 0.01 [get_ports {sum[19]}]
set_load -pin_load 0.01 [get_ports {sum[18]}]
set_load -pin_load 0.01 [get_ports {sum[17]}]
set_load -pin_load 0.01 [get_ports {sum[16]}]
set_load -pin_load 0.01 [get_ports {sum[15]}]
set_load -pin_load 0.01 [get_ports {sum[14]}]
set_load -pin_load 0.01 [get_ports {sum[13]}]
set_load -pin_load 0.01 [get_ports {sum[12]}]
set_load -pin_load 0.01 [get_ports {sum[11]}]
set_load -pin_load 0.01 [get_ports {sum[10]}]
set_load -pin_load 0.01 [get_ports {sum[9]}]
set_load -pin_load 0.01 [get_ports {sum[8]}]
set_load -pin_load 0.01 [get_ports {sum[7]}]
set_load -pin_load 0.01 [get_ports {sum[6]}]
set_load -pin_load 0.01 [get_ports {sum[5]}]
set_load -pin_load 0.01 [get_ports {sum[4]}]
set_load -pin_load 0.01 [get_ports {sum[3]}]
set_load -pin_load 0.01 [get_ports {sum[2]}]
set_load -pin_load 0.01 [get_ports {sum[1]}]
set_load -pin_load 0.01 [get_ports {sum[0]}]
set_load -pin_load 0.01 [get_ports cout]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[127]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[126]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[125]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[124]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[123]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[122]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[121]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[120]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[119]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[118]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[117]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[116]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[115]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[114]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[113]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[112]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[111]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[110]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[109]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[108]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[107]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[106]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[105]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[104]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[103]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[102]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[101]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[100]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[99]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[98]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[97]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[96]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[95]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[94]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[93]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[92]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[91]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[90]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[89]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[88]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[87]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[86]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[85]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[84]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[83]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[82]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[81]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[80]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[79]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[78]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[77]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[76]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[75]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[74]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[73]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[72]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[71]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[70]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[69]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[68]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[67]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[66]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[65]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[64]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[63]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[62]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[61]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[60]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[59]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[58]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[57]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[56]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[55]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[54]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[53]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[52]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[51]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[50]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[49]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[48]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[47]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[46]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[45]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[44]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[43]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[42]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[41]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[40]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[39]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[38]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[37]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[36]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[35]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[34]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[33]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[32]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {A[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[127]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[126]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[125]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[124]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[123]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[122]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[121]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[120]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[119]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[118]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[117]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[116]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[115]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[114]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[113]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[112]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[111]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[110]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[109]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[108]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[107]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[106]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[105]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[104]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[103]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[102]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[101]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[100]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[99]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[98]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[97]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[96]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[95]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[94]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[93]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[92]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[91]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[90]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[89]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[88]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[87]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[86]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[85]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[84]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[83]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[82]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[81]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[80]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[79]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[78]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[77]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[76]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[75]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[74]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[73]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[72]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[71]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[70]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[69]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[68]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[67]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[66]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[65]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[64]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[63]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[62]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[61]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[60]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[59]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[58]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[57]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[56]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[55]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[54]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[53]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[52]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[51]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[50]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[49]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[48]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[47]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[46]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[45]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[44]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[43]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[42]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[41]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[40]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[39]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[38]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[37]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[36]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[35]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[34]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[33]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[32]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {B[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports cin]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[127]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[126]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[125]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[124]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[123]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[122]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[121]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[120]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[119]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[118]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[117]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[116]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[115]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[114]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[113]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[112]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[111]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[110]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[109]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[108]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[107]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[106]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[105]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[104]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[103]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[102]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[101]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[100]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[99]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[98]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[97]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[96]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[95]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[94]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[93]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[92]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[91]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[90]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[89]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[88]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[87]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[86]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[85]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[84]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[83]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[82]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[81]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[80]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[79]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[78]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[77]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[76]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[75]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[74]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[73]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[72]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[71]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[70]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[69]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[68]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[67]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[66]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[65]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[64]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[63]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[62]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[61]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[60]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[59]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[58]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[57]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[56]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[55]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[54]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[53]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[52]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[51]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[50]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[49]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[48]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[47]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[46]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[45]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[44]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[43]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[42]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[41]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[40]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[39]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[38]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[37]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[36]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[35]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[34]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[33]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[32]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[31]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[30]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[29]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[28]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[27]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[26]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[25]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[24]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {sum[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports cout]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[127]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[126]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[125]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[124]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[123]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[122]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[121]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[120]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[119]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[118]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[117]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[116]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[115]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[114]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[113]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[112]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[111]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[110]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[109]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[108]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[107]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[106]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[105]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[104]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[103]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[102]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[101]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[100]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[99]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[98]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[97]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[96]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[95]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[94]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[93]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[92]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[91]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[90]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[89]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[88]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[87]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[86]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[85]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[84]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[83]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[82]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[81]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[80]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[79]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[78]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[77]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[76]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[75]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[74]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[73]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[72]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[71]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[70]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[69]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[68]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[67]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[66]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[65]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[64]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[63]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[62]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[61]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[60]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[59]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[58]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[57]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[56]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[55]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[54]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[53]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[52]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[51]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[50]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[49]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[48]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[47]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[46]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[45]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[44]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[43]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[42]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[41]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[40]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[39]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[38]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[37]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[36]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[35]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[34]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[33]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[32]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[31]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[30]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[29]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[28]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[27]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[26]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[25]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[24]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[23]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[22]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[21]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[20]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[19]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[18]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[17]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[16]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[15]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[14]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[13]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[12]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[11]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[10]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[9]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[8]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[7]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[6]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[5]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[4]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[3]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[2]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[1]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {A[0]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[127]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[126]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[125]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[124]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[123]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[122]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[121]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[120]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[119]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[118]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[117]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[116]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[115]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[114]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[113]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[112]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[111]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[110]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[109]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[108]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[107]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[106]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[105]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[104]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[103]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[102]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[101]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[100]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[99]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[98]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[97]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[96]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[95]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[94]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[93]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[92]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[91]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[90]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[89]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[88]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[87]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[86]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[85]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[84]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[83]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[82]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[81]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[80]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[79]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[78]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[77]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[76]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[75]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[74]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[73]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[72]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[71]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[70]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[69]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[68]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[67]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[66]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[65]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[64]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[63]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[62]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[61]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[60]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[59]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[58]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[57]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[56]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[55]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[54]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[53]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[52]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[51]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[50]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[49]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[48]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[47]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[46]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[45]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[44]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[43]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[42]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[41]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[40]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[39]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[38]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[37]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[36]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[35]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[34]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[33]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[32]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[31]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[30]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[29]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[28]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[27]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[26]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[25]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[24]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[23]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[22]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[21]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[20]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[19]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[18]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[17]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[16]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[15]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[14]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[13]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[12]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[11]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[10]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[9]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[8]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[7]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[6]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[5]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[4]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[3]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[2]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[1]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {B[0]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports cin]
set_wire_load_mode "enclosed"
