
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr 17 2026 19:31:40 IST (Apr 17 2026 14:01:40 UTC)

// Verification Directory fv/RCA64 

module full_adder(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_1, n_6, n_11, n_41, n_42, n_43, n_45;
  OAI21X1 g71__2398(.A0 (n_11), .A1 (n_45), .B0 (n_6), .Y (sum));
  NAND2XL g72__5107(.A (n_11), .B (n_45), .Y (n_6));
  DLY2X1 fopt(.A (a), .Y (n_1));
  CLKBUFX2 fopt79(.A (cin), .Y (n_11));
  OAI21X2 g74(.A0 (n_41), .A1 (n_42), .B0 (n_43), .Y (cout));
  CLKINVX1 g94(.A (b), .Y (n_41));
  NOR2X2 g77(.A (a), .B (cin), .Y (n_42));
  NAND2X1 g76(.A (a), .B (cin), .Y (n_43));
  MXI2XL g75(.A (b), .B (n_41), .S0 (n_1), .Y (n_45));
endmodule

module full_adder_126(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_5, n_10, n_17, n_18, n_19, n_21;
  OAI21X1 g67__6783(.A0 (n_10), .A1 (n_21), .B0 (n_5), .Y (sum));
  NAND2XL g68__3680(.A (n_10), .B (n_21), .Y (n_5));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NAND2X2 g24(.A (n_17), .B (n_19), .Y (cout));
  NAND2XL g26(.A (b), .B (a), .Y (n_17));
  NAND2X2 g25(.A (n_18), .B (cin), .Y (n_19));
  OR2XL g27(.A (a), .B (b), .Y (n_18));
  XNOR2XL g2(.A (b), .B (a), .Y (n_21));
endmodule

module full_adder_125(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_1, n_3, n_13, n_14, n_15;
  OAI21X1 g68__8246(.A0 (n_0), .A1 (n_1), .B0 (n_3), .Y (sum));
  NAND2XL g69__7098(.A (n_0), .B (n_1), .Y (n_3));
  XNOR2XL g71__1881(.A (a), .B (b), .Y (n_1));
  DLY2X1 fopt(.A (cin), .Y (n_0));
  NOR2X2 g37(.A (n_13), .B (n_15), .Y (cout));
  NOR2X4 g39(.A (a), .B (b), .Y (n_13));
  NOR2X2 g38(.A (n_14), .B (cin), .Y (n_15));
  AND2X1 g40(.A (b), .B (a), .Y (n_14));
endmodule

module full_adder_124(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_3, n_8, n_11, n_12, n_14, n_15;
  OAI21X1 g67__5115(.A0 (n_8), .A1 (n_0), .B0 (n_3), .Y (sum));
  NAND2XL g68__7482(.A (n_8), .B (n_0), .Y (n_3));
  XNOR2XL g71__6161(.A (a), .B (b), .Y (n_0));
  DLY2X1 fopt(.A (cin), .Y (n_8));
  AND2X1 g30(.A (a), .B (b), .Y (n_11));
  OR2X1 g29(.A (a), .B (b), .Y (n_12));
  NOR2X2 g33(.A (n_14), .B (n_15), .Y (cout));
  CLKINVX1 g35(.A (n_12), .Y (n_14));
  NOR2X2 g34(.A (n_11), .B (cin), .Y (n_15));
endmodule

module full_adder_123(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_5, n_10, n_13, n_14, n_15, n_22, n_23;
  wire n_25;
  OAI21X1 g67__9315(.A0 (n_10), .A1 (n_0), .B0 (n_5), .Y (sum));
  NAND2XL g68__9945(.A (n_10), .B (n_0), .Y (n_5));
  XNOR2XL g2__2346(.A (n_15), .B (n_14), .Y (n_0));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NAND2X2 g64(.A (b), .B (a), .Y (n_13));
  CLKINVX1 g67(.A (b), .Y (n_14));
  CLKINVX1 g66(.A (a), .Y (n_15));
  NAND2X2 g20(.A (n_13), .B (n_23), .Y (cout));
  NAND2X2 g21(.A (n_22), .B (cin), .Y (n_23));
  CLKINVX2 g22(.A (n_25), .Y (n_22));
  AND2X1 g2(.A (n_14), .B (n_15), .Y (n_25));
endmodule

module full_adder_122(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_12, n_13, n_28, n_30, n_39, n_40, n_43;
  wire n_44;
  XNOR2XL g2__5477(.A (n_13), .B (n_12), .Y (n_0));
  CLKINVX1 g68(.A (b), .Y (n_12));
  CLKINVX1 g67(.A (a), .Y (n_13));
  AND2X1 g34(.A (n_13), .B (n_12), .Y (n_28));
  NAND2X2 g33(.A (b), .B (a), .Y (n_30));
  MXI2XL g41(.A (n_40), .B (n_39), .S0 (n_0), .Y (sum));
  INVXL g42(.A (n_39), .Y (n_40));
  NAND2X2 g20(.A (n_30), .B (n_44), .Y (cout));
  NAND2X2 g21(.A (n_43), .B (cin), .Y (n_44));
  CLKINVX1 g22(.A (n_28), .Y (n_43));
  INVXL g23(.A (cin), .Y (n_39));
endmodule

module full_adder_121(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_1, n_11, n_12, n_27, n_28;
  XNOR2XL g71__4319(.A (a), .B (b), .Y (n_1));
  DLY2X1 fopt(.A (cin), .Y (n_0));
  AND2X1 g30(.A (a), .B (b), .Y (n_11));
  OR2X1 g29(.A (a), .B (b), .Y (n_12));
  NOR2X2 g76(.A (n_27), .B (n_28), .Y (cout));
  CLKINVX1 g35(.A (n_12), .Y (n_27));
  NOR2X2 g77(.A (n_11), .B (cin), .Y (n_28));
  XNOR2X1 g2(.A (n_0), .B (n_1), .Y (sum));
endmodule

module full_adder_120(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_5, n_13, n_16, n_17, n_18, n_19, n_22;
  wire n_25, n_26;
  OAI21X1 g67__8428(.A0 (n_13), .A1 (n_0), .B0 (n_5), .Y (sum));
  NAND2XL g68__5526(.A (n_13), .B (n_0), .Y (n_5));
  XNOR2XL g2__3680(.A (n_18), .B (n_17), .Y (n_0));
  DLY2X1 fopt2(.A (cin), .Y (n_13));
  NAND2X2 g65(.A (b), .B (a), .Y (n_16));
  NAND2XL g66(.A (n_17), .B (n_18), .Y (n_19));
  CLKINVX1 g68(.A (b), .Y (n_17));
  CLKINVX1 g67(.A (a), .Y (n_18));
  CLKINVX1 g16(.A (n_19), .Y (n_22));
  NAND2X2 g20(.A (n_16), .B (n_26), .Y (cout));
  NAND2X2 g21(.A (n_25), .B (cin), .Y (n_26));
  CLKINVX2 g22(.A (n_22), .Y (n_25));
endmodule

module full_adder_119(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_1, n_2, n_4, n_10, n_14, n_17, n_20, n_21;
  wire n_22;
  OAI21X1 g68__1617(.A0 (n_1), .A1 (n_2), .B0 (n_4), .Y (sum));
  NAND2X1 g69__2802(.A (n_1), .B (n_2), .Y (n_4));
  XNOR2X1 g71__5122(.A (a), .B (b), .Y (n_2));
  DLY2X1 fopt(.A (cin), .Y (n_1));
  NOR2XL g62(.A (b), .B (a), .Y (n_10));
  INVXL g24(.A (n_10), .Y (n_14));
  CLKINVX1 g74(.A (n_14), .Y (n_17));
  NOR2X2 g76(.A (n_17), .B (n_22), .Y (cout));
  NOR2X2 g1(.A (n_21), .B (cin), .Y (n_22));
  CLKINVX1 g2(.A (n_20), .Y (n_21));
  NAND2XL g77(.A (b), .B (a), .Y (n_20));
endmodule

module full_adder_118(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_5, n_10, n_17, n_18, n_19, n_24;
  OAI21X1 g67__8246(.A0 (n_10), .A1 (n_24), .B0 (n_5), .Y (sum));
  NAND2X1 g68__7098(.A (n_10), .B (n_24), .Y (n_5));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NAND2X2 g20(.A (n_17), .B (n_19), .Y (cout));
  NAND2X2 g22(.A (b), .B (a), .Y (n_17));
  NAND2X2 g21(.A (n_18), .B (cin), .Y (n_19));
  OR2X1 g23(.A (b), .B (a), .Y (n_18));
  XNOR2X1 g2(.A (b), .B (a), .Y (n_24));
endmodule

module full_adder_117(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_5, n_10, n_12, n_13, n_14, n_15;
  OAI21X1 g67__4733(.A0 (n_10), .A1 (n_0), .B0 (n_5), .Y (sum));
  NAND2X1 g68__6161(.A (n_10), .B (n_0), .Y (n_5));
  CLKXOR2X1 g2__2346(.A (n_13), .B (a), .Y (n_0));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NAND2X2 g61(.A (n_12), .B (n_15), .Y (cout));
  NAND2X2 g63(.A (b), .B (a), .Y (n_12));
  NAND2X2 g62(.A (n_14), .B (cin), .Y (n_15));
  NAND2BX4 g64(.AN (a), .B (n_13), .Y (n_14));
  CLKINVX1 g65(.A (b), .Y (n_13));
endmodule

module full_adder_116(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_3, n_8, n_39, n_40, n_41;
  OAI21X1 g67__1666(.A0 (n_8), .A1 (n_0), .B0 (n_3), .Y (sum));
  NAND2X1 g68__7410(.A (n_8), .B (n_0), .Y (n_3));
  CLKINVX2 g69(.A (n_41), .Y (cout));
  XNOR2X1 g71__5477(.A (a), .B (b), .Y (n_0));
  DLY2X1 fopt(.A (cin), .Y (n_8));
  OAI21X2 g32(.A0 (n_39), .A1 (cin), .B0 (n_40), .Y (n_41));
  AND2X1 g34(.A (b), .B (a), .Y (n_39));
  OR2X1 g33(.A (b), .B (a), .Y (n_40));
endmodule

module full_adder_115(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_10, n_17, n_18, n_22, n_23, n_28, n_31;
  OR2X6 g64(.A (b), .B (a), .Y (n_10));
  NAND2X2 g13(.A (n_17), .B (n_18), .Y (cout));
  CLKINVX1 g76(.A (n_28), .Y (n_17));
  NAND2X2 g77(.A (n_10), .B (cin), .Y (n_18));
  OAI21X1 g29(.A0 (n_31), .A1 (n_22), .B0 (n_23), .Y (sum));
  DLY2X1 g1(.A (cin), .Y (n_22));
  NAND2X1 g30(.A (n_31), .B (n_22), .Y (n_23));
  AND2XL g2(.A (b), .B (a), .Y (n_28));
  XNOR2X1 g81(.A (a), .B (b), .Y (n_31));
endmodule

module full_adder_114(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_17, n_18, n_19, n_22, n_24;
  NAND2X2 g28(.A (n_17), .B (n_19), .Y (cout));
  NAND2X2 g30(.A (a), .B (b), .Y (n_17));
  NAND2X2 g29(.A (n_18), .B (cin), .Y (n_19));
  OR2X4 g31(.A (b), .B (a), .Y (n_18));
  CLKXOR2X1 g34(.A (n_24), .B (n_22), .Y (sum));
  DLY2X1 g1(.A (cin), .Y (n_22));
  XOR2XL g2(.A (b), .B (a), .Y (n_24));
endmodule

module full_adder_113(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_11, n_13, n_15, n_18, n_19, n_21, n_22, n_23;
  CLKAND2X2 g40(.A (b), .B (a), .Y (n_11));
  NOR2XL g39(.A (a), .B (b), .Y (n_13));
  INVXL g26(.A (n_13), .Y (n_15));
  NOR2X2 g23(.A (n_18), .B (n_19), .Y (cout));
  CLKINVX1 g72(.A (n_15), .Y (n_18));
  NOR2X2 g73(.A (n_11), .B (cin), .Y (n_19));
  OAI21X1 g29(.A0 (n_21), .A1 (n_22), .B0 (n_23), .Y (sum));
  XNOR2XL g31(.A (a), .B (b), .Y (n_21));
  DLY2X1 g1(.A (cin), .Y (n_22));
  NAND2X1 g30(.A (n_21), .B (n_22), .Y (n_23));
endmodule

module full_adder_112(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_11, n_12, n_16, n_24, n_25, n_26;
  OAI22XL g69__6131(.A0 (n_12), .A1 (b), .B0 (n_11), .B1 (a), .Y (n_4));
  XNOR2X1 g2__1881(.A (n_16), .B (n_4), .Y (sum));
  CLKINVX1 g69(.A (b), .Y (n_11));
  CLKINVX1 g67(.A (a), .Y (n_12));
  INVXL g68(.A (cin), .Y (n_16));
  NAND2X2 g32(.A (n_24), .B (n_26), .Y (cout));
  NAND2X2 g34(.A (b), .B (a), .Y (n_24));
  NAND2X2 g33(.A (n_25), .B (cin), .Y (n_26));
  NAND2X2 g35(.A (n_11), .B (n_12), .Y (n_25));
endmodule

module full_adder_111(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_32, n_37, n_38, n_39, n_43, n_44, n_45;
  INVX2 fopt1(.A (n_39), .Y (cout));
  NAND2XL g32(.A (a), .B (b), .Y (n_32));
  OAI21X2 g76(.A0 (n_37), .A1 (cin), .B0 (n_38), .Y (n_39));
  AND2X1 g34(.A (b), .B (a), .Y (n_37));
  OR2X1 g33(.A (b), .B (a), .Y (n_38));
  OAI21X1 g79(.A0 (n_43), .A1 (n_44), .B0 (n_45), .Y (sum));
  OAI21XL g80(.A0 (b), .A1 (a), .B0 (n_32), .Y (n_43));
  DLY2X1 g81(.A (cin), .Y (n_44));
  NAND2X1 g82(.A (n_44), .B (n_43), .Y (n_45));
endmodule

module full_adder_110(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_13, n_14, n_15, n_16, n_19, n_20, n_23;
  wire n_24;
  OAI22XL g69__9315(.A0 (n_15), .A1 (b), .B0 (n_14), .B1 (a), .Y (n_4));
  XNOR2X1 g2__9945(.A (n_19), .B (n_4), .Y (sum));
  NAND2X2 g65(.A (b), .B (a), .Y (n_13));
  NAND2XL g66(.A (n_14), .B (n_15), .Y (n_16));
  CLKINVX1 g69(.A (b), .Y (n_14));
  CLKINVX1 g67(.A (a), .Y (n_15));
  INVXL g68(.A (cin), .Y (n_19));
  CLKINVX1 g16(.A (n_16), .Y (n_20));
  NAND2X2 g20(.A (n_13), .B (n_24), .Y (cout));
  NAND2X2 g21(.A (n_23), .B (cin), .Y (n_24));
  CLKINVX2 g22(.A (n_20), .Y (n_23));
endmodule

module full_adder_109(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_1, n_2, n_4, n_10, n_14, n_17, n_20, n_21;
  wire n_22;
  OAI21X1 g68__2883(.A0 (n_1), .A1 (n_2), .B0 (n_4), .Y (sum));
  NAND2X1 g69__2346(.A (n_1), .B (n_2), .Y (n_4));
  XNOR2XL g71__7410(.A (a), .B (b), .Y (n_2));
  DLY2X1 fopt(.A (cin), .Y (n_1));
  NOR2XL g62(.A (b), .B (a), .Y (n_10));
  INVXL g24(.A (n_10), .Y (n_14));
  CLKINVX1 g74(.A (n_14), .Y (n_17));
  NOR2X2 g76(.A (n_17), .B (n_22), .Y (cout));
  NOR2X2 g1(.A (n_21), .B (cin), .Y (n_22));
  CLKINVX1 g2(.A (n_20), .Y (n_21));
  NAND2XL g77(.A (b), .B (a), .Y (n_20));
endmodule

module full_adder_108(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_12, n_13, n_14, n_15, n_25, n_26, n_27;
  NAND2X2 g61(.A (n_12), .B (n_15), .Y (cout));
  NAND2X2 g63(.A (a), .B (b), .Y (n_12));
  NAND2X2 g62(.A (n_14), .B (cin), .Y (n_15));
  NAND2BX2 g64(.AN (a), .B (n_13), .Y (n_14));
  CLKINVX1 g65(.A (b), .Y (n_13));
  OAI21X1 g41(.A0 (n_25), .A1 (n_26), .B0 (n_27), .Y (sum));
  MXI2XL g43(.A (b), .B (n_13), .S0 (a), .Y (n_25));
  DLY2X1 g1(.A (cin), .Y (n_26));
  NAND2X1 g42(.A (n_25), .B (n_26), .Y (n_27));
endmodule

module full_adder_107(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_12, n_13, n_14, n_15, n_25, n_26, n_27;
  NAND2X2 g61(.A (n_12), .B (n_15), .Y (cout));
  NAND2X2 g63(.A (a), .B (b), .Y (n_12));
  NAND2X2 g62(.A (n_14), .B (cin), .Y (n_15));
  NAND2BX4 g64(.AN (a), .B (n_13), .Y (n_14));
  CLKINVX1 g65(.A (b), .Y (n_13));
  OAI21X1 g41(.A0 (n_25), .A1 (n_26), .B0 (n_27), .Y (sum));
  MXI2XL g43(.A (b), .B (n_13), .S0 (a), .Y (n_25));
  DLY2X1 g1(.A (cin), .Y (n_26));
  NAND2XL g42(.A (n_25), .B (n_26), .Y (n_27));
endmodule

module full_adder_106(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_2, n_9, n_14, n_15, n_18, n_21, n_22;
  OAI21X1 g68__1705(.A0 (n_9), .A1 (n_0), .B0 (n_2), .Y (sum));
  NAND2X1 g69__5122(.A (n_9), .B (n_0), .Y (n_2));
  XNOR2XL g71__7098(.A (a), .B (b), .Y (n_0));
  DLY2X1 fopt72(.A (cin), .Y (n_9));
  NOR2XL g39(.A (a), .B (b), .Y (n_14));
  CLKAND2X2 g40(.A (b), .B (a), .Y (n_15));
  CLKINVX1 g26(.A (n_14), .Y (n_18));
  NOR2X2 g33(.A (n_21), .B (n_22), .Y (cout));
  CLKINVX1 g35(.A (n_18), .Y (n_21));
  NOR2X2 g34(.A (n_15), .B (cin), .Y (n_22));
endmodule

module full_adder_105(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_22, n_23, n_26, n_27, n_30, n_31, n_34, n_35;
  wire n_42;
  NOR2XL g39(.A (a), .B (b), .Y (n_22));
  NAND2XL g40(.A (a), .B (b), .Y (n_23));
  CLKINVX1 g24(.A (n_23), .Y (n_26));
  CLKINVX1 g25(.A (n_22), .Y (n_27));
  NOR2X2 g33(.A (n_30), .B (n_31), .Y (cout));
  CLKINVX1 g35(.A (n_27), .Y (n_30));
  NOR2X2 g34(.A (n_26), .B (cin), .Y (n_31));
  OAI21X1 g41(.A0 (n_42), .A1 (n_34), .B0 (n_35), .Y (sum));
  DLY2X1 g1(.A (cin), .Y (n_34));
  NAND2X1 g42(.A (n_42), .B (n_34), .Y (n_35));
  XNOR2X1 g2(.A (b), .B (a), .Y (n_42));
endmodule

module full_adder_104(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_10, n_14, n_15, n_16, n_18, n_19;
  CLKINVX1 g65(.A (b), .Y (n_10));
  NAND2X2 g22(.A (n_14), .B (n_16), .Y (cout));
  NAND2X2 g24(.A (b), .B (a), .Y (n_14));
  NAND2X2 g23(.A (n_15), .B (cin), .Y (n_16));
  NAND2BX4 g25(.AN (a), .B (n_10), .Y (n_15));
  CLKXOR2X1 g34(.A (n_18), .B (n_19), .Y (sum));
  MXI2XL g35(.A (n_10), .B (b), .S0 (a), .Y (n_18));
  DLY2X1 g1(.A (cin), .Y (n_19));
endmodule

module full_adder_103(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_11, n_12, n_15, n_18, n_19, n_21, n_22, n_23;
  NOR2XL g39(.A (a), .B (b), .Y (n_11));
  AND2X1 g40(.A (b), .B (a), .Y (n_12));
  INVXL g26(.A (n_11), .Y (n_15));
  NOR2X2 g23(.A (n_18), .B (n_19), .Y (cout));
  CLKINVX1 g72(.A (n_15), .Y (n_18));
  NOR2X2 g73(.A (n_12), .B (cin), .Y (n_19));
  OAI21X1 g29(.A0 (n_21), .A1 (n_22), .B0 (n_23), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_21));
  DLY2X1 g1(.A (cin), .Y (n_22));
  NAND2X1 g30(.A (n_21), .B (n_22), .Y (n_23));
endmodule

module full_adder_102(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_10, n_11, n_12, n_13, n_14, n_16;
  OAI22XL g69__5107(.A0 (n_12), .A1 (b), .B0 (n_11), .B1 (a), .Y (n_4));
  XNOR2X1 g2__6260(.A (n_16), .B (n_4), .Y (sum));
  NAND2X2 g62(.A (n_10), .B (n_14), .Y (cout));
  NAND2X2 g64(.A (b), .B (a), .Y (n_10));
  NAND2X2 g63(.A (n_13), .B (cin), .Y (n_14));
  NAND2X2 g65(.A (n_11), .B (n_12), .Y (n_13));
  CLKINVX1 g68(.A (b), .Y (n_11));
  CLKINVX1 g66(.A (a), .Y (n_12));
  INVXL g67(.A (cin), .Y (n_16));
endmodule

module full_adder_101(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_9, n_12, n_13, n_14, n_15, n_16;
  OAI22XL g69__8428(.A0 (n_14), .A1 (b), .B0 (n_13), .B1 (a), .Y (n_4));
  XNOR2X1 g2__5526(.A (n_9), .B (n_4), .Y (sum));
  INVXL fopt(.A (cin), .Y (n_9));
  NAND2X2 g62(.A (n_12), .B (n_16), .Y (cout));
  NAND2X2 g64(.A (b), .B (a), .Y (n_12));
  NAND2X2 g63(.A (n_15), .B (cin), .Y (n_16));
  NAND2X2 g65(.A (n_13), .B (n_14), .Y (n_15));
  CLKINVX1 g67(.A (b), .Y (n_13));
  CLKINVX1 g66(.A (a), .Y (n_14));
endmodule

module full_adder_100(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_8, n_9, n_15, n_16, n_18, n_19, n_20, n_21;
  AND2X1 g30(.A (a), .B (b), .Y (n_8));
  OR2X1 g29(.A (a), .B (b), .Y (n_9));
  NOR2X2 g33(.A (n_15), .B (n_16), .Y (cout));
  CLKINVX1 g35(.A (n_9), .Y (n_15));
  NOR2X2 g34(.A (n_8), .B (cin), .Y (n_16));
  OAI21X1 g72(.A0 (n_19), .A1 (n_20), .B0 (n_21), .Y (sum));
  OAI21XL g31(.A0 (b), .A1 (a), .B0 (n_18), .Y (n_19));
  NAND2XL g32(.A (a), .B (b), .Y (n_18));
  DLY2X1 g1(.A (cin), .Y (n_20));
  NAND2X1 g73(.A (n_19), .B (n_20), .Y (n_21));
endmodule

module full_adder_99(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_10, n_11, n_12, n_13, n_16, n_17, n_20;
  wire n_21;
  OAI22XL g69__1705(.A0 (n_12), .A1 (b), .B0 (n_11), .B1 (a), .Y (n_4));
  XNOR2X1 g2__5122(.A (n_16), .B (n_4), .Y (sum));
  NAND2X2 g64(.A (b), .B (a), .Y (n_10));
  NAND2XL g65(.A (n_11), .B (n_12), .Y (n_13));
  CLKINVX1 g68(.A (b), .Y (n_11));
  CLKINVX1 g66(.A (a), .Y (n_12));
  INVXL g67(.A (cin), .Y (n_16));
  CLKINVX1 g16(.A (n_13), .Y (n_17));
  NAND2X2 g20(.A (n_10), .B (n_21), .Y (cout));
  NAND2X2 g21(.A (n_20), .B (cin), .Y (n_21));
  CLKINVX1 g22(.A (n_17), .Y (n_20));
endmodule

module full_adder_98(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_7, n_9, n_11, n_14, n_17, n_18, n_20, n_21;
  wire n_22;
  NAND2XL g64(.A (b), .B (a), .Y (n_7));
  NOR2XL g63(.A (b), .B (a), .Y (n_9));
  INVXL g24(.A (n_9), .Y (n_11));
  CLKINVX1 g72(.A (n_11), .Y (n_14));
  NOR2X2 g22(.A (n_14), .B (n_18), .Y (cout));
  NOR2X2 g23(.A (n_17), .B (cin), .Y (n_18));
  CLKINVX1 g74(.A (n_7), .Y (n_17));
  OAI21X1 g29(.A0 (n_20), .A1 (n_21), .B0 (n_22), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_20));
  DLY2X1 g1(.A (cin), .Y (n_21));
  NAND2X1 g30(.A (n_20), .B (n_21), .Y (n_22));
endmodule

module full_adder_97(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_10, n_23, n_24, n_25, n_27, n_28;
  CLKINVX1 g66(.A (b), .Y (n_10));
  NAND2X2 g22(.A (n_23), .B (n_25), .Y (cout));
  NAND2X2 g24(.A (b), .B (a), .Y (n_23));
  NAND2X2 g23(.A (n_24), .B (cin), .Y (n_25));
  NAND2BX2 g25(.AN (a), .B (n_10), .Y (n_24));
  CLKXOR2X1 g34(.A (n_27), .B (n_28), .Y (sum));
  MXI2XL g35(.A (n_10), .B (b), .S0 (a), .Y (n_27));
  DLY2X1 g1(.A (cin), .Y (n_28));
endmodule

module full_adder_96(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_12, n_13, n_23, n_24, n_27, n_31;
  AND2X1 g30(.A (a), .B (b), .Y (n_12));
  OR2X1 g29(.A (a), .B (b), .Y (n_13));
  NOR2X2 g33(.A (n_23), .B (n_24), .Y (cout));
  CLKINVX1 g35(.A (n_13), .Y (n_23));
  NOR2X2 g34(.A (n_12), .B (cin), .Y (n_24));
  CLKXOR2X1 g74(.A (n_31), .B (n_27), .Y (sum));
  DLY2X1 g1(.A (cin), .Y (n_27));
  XOR2XL g2(.A (b), .B (a), .Y (n_31));
endmodule

module full_adder_95(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_11, n_12, n_18, n_20, n_21, n_22;
  AND2X1 g23(.A (b), .B (a), .Y (n_11));
  OR2X1 g22(.A (b), .B (a), .Y (n_12));
  CLKINVX2 g33(.A (n_18), .Y (cout));
  OAI21X2 g34(.A0 (n_11), .A1 (cin), .B0 (n_12), .Y (n_18));
  OAI21X1 g29(.A0 (n_20), .A1 (n_21), .B0 (n_22), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_20));
  DLY2X1 g1(.A (cin), .Y (n_21));
  NAND2X1 g30(.A (n_20), .B (n_21), .Y (n_22));
endmodule

module full_adder_94(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_6, n_11, n_20, n_21, n_22, n_27;
  OAI21X1 g63__2398(.A0 (n_11), .A1 (n_27), .B0 (n_6), .Y (sum));
  NAND2X1 g64__5107(.A (n_11), .B (n_27), .Y (n_6));
  DLY2X1 fopt(.A (cin), .Y (n_11));
  NAND2X2 g31(.A (n_20), .B (n_22), .Y (cout));
  NAND2X2 g33(.A (b), .B (a), .Y (n_20));
  NAND2X2 g32(.A (n_21), .B (cin), .Y (n_22));
  OR2X6 g34(.A (a), .B (b), .Y (n_21));
  XNOR2X1 g2(.A (a), .B (b), .Y (n_27));
endmodule

module full_adder_93(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_21, n_22, n_23, n_25, n_26, n_27;
  NAND2X2 g20(.A (n_21), .B (n_23), .Y (cout));
  NAND2X2 g22(.A (b), .B (a), .Y (n_21));
  NAND2X2 g21(.A (n_22), .B (cin), .Y (n_23));
  OR2X4 g23(.A (a), .B (b), .Y (n_22));
  OAI21X1 g29(.A0 (n_25), .A1 (n_26), .B0 (n_27), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_25));
  DLY2X1 g1(.A (cin), .Y (n_26));
  NAND2X1 g30(.A (n_25), .B (n_26), .Y (n_27));
endmodule

module full_adder_92(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_10, n_11, n_12, n_13, n_14, n_16;
  OAI22XL g61__1617(.A0 (n_12), .A1 (b), .B0 (n_11), .B1 (a), .Y (n_4));
  XNOR2X1 g2__2802(.A (n_16), .B (n_4), .Y (sum));
  NAND2X2 g63(.A (n_10), .B (n_14), .Y (cout));
  NAND2X2 g66(.A (b), .B (a), .Y (n_10));
  NAND2X2 g67(.A (n_13), .B (cin), .Y (n_14));
  NAND2X2 g68(.A (n_11), .B (n_12), .Y (n_13));
  CLKINVX1 g69(.A (b), .Y (n_11));
  CLKINVX1 g70(.A (a), .Y (n_12));
  INVXL g71(.A (cin), .Y (n_16));
endmodule

module full_adder_91(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_8, n_9, n_28, n_29, n_37, n_38, n_39;
  OR2XL g29(.A (a), .B (b), .Y (n_9));
  NOR2X4 g33(.A (n_28), .B (n_29), .Y (cout));
  CLKINVX1 g35(.A (n_9), .Y (n_28));
  NOR2X2 g34(.A (n_8), .B (cin), .Y (n_29));
  OAI21X1 g66(.A0 (n_37), .A1 (n_38), .B0 (n_39), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_37));
  DLY2X1 g1(.A (cin), .Y (n_38));
  NAND2X1 g30(.A (n_37), .B (n_38), .Y (n_39));
  CLKAND2X2 g68(.A (a), .B (b), .Y (n_8));
endmodule

module full_adder_90(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_10, n_11, n_12, n_13, n_16, n_17, n_20;
  wire n_21;
  OAI22XL g61__6131(.A0 (n_12), .A1 (b), .B0 (n_11), .B1 (a), .Y (n_4));
  XNOR2X1 g2__1881(.A (n_16), .B (n_4), .Y (sum));
  NAND2X2 g66(.A (b), .B (a), .Y (n_10));
  NAND2XL g68(.A (n_11), .B (n_12), .Y (n_13));
  CLKINVX1 g69(.A (b), .Y (n_11));
  CLKINVX1 g70(.A (a), .Y (n_12));
  INVXL g71(.A (cin), .Y (n_16));
  CLKINVX1 g16(.A (n_13), .Y (n_17));
  NAND2X2 g20(.A (n_10), .B (n_21), .Y (cout));
  NAND2X2 g21(.A (n_20), .B (cin), .Y (n_21));
  CLKINVX2 g22(.A (n_17), .Y (n_20));
endmodule

module full_adder_89(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_11, n_12, n_18, n_19, n_21, n_22, n_23, n_24;
  OR2XL g33(.A (b), .B (a), .Y (n_12));
  NOR2X2 g70(.A (n_18), .B (n_19), .Y (cout));
  CLKINVX1 g35(.A (n_12), .Y (n_18));
  NOR2X2 g34(.A (n_11), .B (cin), .Y (n_19));
  CLKAND2X2 g72(.A (b), .B (a), .Y (n_11));
  OAI21X1 g29(.A0 (n_22), .A1 (n_23), .B0 (n_24), .Y (sum));
  OAI21X1 g31(.A0 (b), .A1 (a), .B0 (n_21), .Y (n_22));
  NAND2XL g32(.A (a), .B (b), .Y (n_21));
  DLY2X1 g1(.A (cin), .Y (n_23));
  NAND2XL g30(.A (n_22), .B (n_23), .Y (n_24));
endmodule

module full_adder_88(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_10, n_11, n_12, n_13, n_16, n_17, n_20;
  wire n_21;
  OAI22XL g61__9315(.A0 (n_12), .A1 (b), .B0 (n_11), .B1 (a), .Y (n_4));
  XNOR2X1 g2__9945(.A (n_16), .B (n_4), .Y (sum));
  NAND2X2 g66(.A (b), .B (a), .Y (n_10));
  NAND2XL g67(.A (n_11), .B (n_12), .Y (n_13));
  CLKINVX1 g68(.A (b), .Y (n_11));
  CLKINVX1 g69(.A (a), .Y (n_12));
  INVXL g70(.A (cin), .Y (n_16));
  CLKINVX1 g16(.A (n_13), .Y (n_17));
  NAND2X2 g20(.A (n_10), .B (n_21), .Y (cout));
  NAND2X2 g21(.A (n_20), .B (cin), .Y (n_21));
  CLKINVX2 g22(.A (n_17), .Y (n_20));
endmodule

module full_adder_87(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_7, n_8, n_10, n_11, n_13, n_14, n_15;
  CLKAND2X2 g30(.A (a), .B (b), .Y (n_7));
  OR2X1 g29(.A (a), .B (b), .Y (n_8));
  NOR2X2 g33(.A (n_10), .B (n_11), .Y (cout));
  CLKINVX1 g35(.A (n_8), .Y (n_10));
  NOR2X2 g34(.A (n_7), .B (cin), .Y (n_11));
  OAI21X1 g64(.A0 (n_13), .A1 (n_14), .B0 (n_15), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_13));
  DLY2X1 g1(.A (cin), .Y (n_14));
  NAND2XL g65(.A (n_13), .B (n_14), .Y (n_15));
endmodule

module full_adder_86(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_15, n_16, n_19, n_22, n_23, n_26, n_33;
  NOR2XL g39(.A (a), .B (b), .Y (n_15));
  AND2X1 g40(.A (b), .B (a), .Y (n_16));
  INVXL g26(.A (n_15), .Y (n_19));
  NOR2X2 g23(.A (n_22), .B (n_23), .Y (cout));
  CLKINVX1 g66(.A (n_19), .Y (n_22));
  NOR2X2 g67(.A (n_16), .B (cin), .Y (n_23));
  CLKXOR2X1 g34(.A (n_33), .B (n_26), .Y (sum));
  DLY2X1 g1(.A (cin), .Y (n_26));
  XOR2XL g2(.A (b), .B (a), .Y (n_33));
endmodule

module full_adder_85(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_15, n_16, n_19, n_22, n_23, n_28, n_33;
  NOR2XL g39(.A (a), .B (b), .Y (n_15));
  AND2X1 g40(.A (b), .B (a), .Y (n_16));
  INVXL g26(.A (n_15), .Y (n_19));
  NOR2X2 g23(.A (n_22), .B (n_23), .Y (cout));
  CLKINVX1 g66(.A (n_19), .Y (n_22));
  NOR2X2 g67(.A (n_16), .B (cin), .Y (n_23));
  CLKXOR2X1 g34(.A (n_33), .B (n_28), .Y (sum));
  DLY2X1 g1(.A (cin), .Y (n_28));
  XOR2XL g2(.A (b), .B (a), .Y (n_33));
endmodule

module full_adder_84(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_11, n_12, n_15, n_18, n_19, n_23, n_24, n_25;
  NOR2XL g39(.A (a), .B (b), .Y (n_11));
  AND2X1 g40(.A (b), .B (a), .Y (n_12));
  INVXL g26(.A (n_11), .Y (n_15));
  NOR2X2 g23(.A (n_18), .B (n_19), .Y (cout));
  CLKINVX1 g64(.A (n_15), .Y (n_18));
  NOR2X2 g65(.A (n_12), .B (cin), .Y (n_19));
  OAI21X1 g29(.A0 (n_23), .A1 (n_24), .B0 (n_25), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_23));
  DLY2X1 g1(.A (cin), .Y (n_24));
  NAND2X1 g30(.A (n_23), .B (n_24), .Y (n_25));
endmodule

module full_adder_83(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_14, n_15, n_16, n_17, n_20, n_23, n_24, n_26;
  wire n_27, n_28;
  NAND2X2 g64(.A (b), .B (a), .Y (n_14));
  NAND2XL g67(.A (n_15), .B (n_16), .Y (n_17));
  CLKINVX1 g68(.A (b), .Y (n_15));
  CLKINVX1 g69(.A (a), .Y (n_16));
  CLKINVX1 g16(.A (n_17), .Y (n_20));
  NAND2X2 g20(.A (n_14), .B (n_24), .Y (cout));
  NAND2X2 g21(.A (n_23), .B (cin), .Y (n_24));
  CLKINVX1 g22(.A (n_20), .Y (n_23));
  OAI21X1 g42(.A0 (n_26), .A1 (n_27), .B0 (n_28), .Y (sum));
  AOI22XL g44(.A0 (b), .A1 (n_16), .B0 (a), .B1 (n_15), .Y (n_26));
  DLY2X1 g1(.A (cin), .Y (n_27));
  NAND2X1 g43(.A (n_26), .B (n_27), .Y (n_28));
endmodule

module full_adder_82(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_7, n_8, n_10, n_11, n_13, n_14, n_15;
  CLKAND2X2 g30(.A (a), .B (b), .Y (n_7));
  OR2X1 g29(.A (a), .B (b), .Y (n_8));
  NOR2X2 g33(.A (n_10), .B (n_11), .Y (cout));
  CLKINVX1 g35(.A (n_8), .Y (n_10));
  NOR2X2 g34(.A (n_7), .B (cin), .Y (n_11));
  OAI21X1 g64(.A0 (n_13), .A1 (n_14), .B0 (n_15), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_13));
  DLY2X1 g1(.A (cin), .Y (n_14));
  NAND2X1 g65(.A (n_13), .B (n_14), .Y (n_15));
endmodule

module full_adder_81(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_8, n_9, n_11, n_12, n_14, n_15, n_16;
  AND2X1 g30(.A (a), .B (b), .Y (n_8));
  OR2X1 g29(.A (a), .B (b), .Y (n_9));
  NOR2X2 g33(.A (n_11), .B (n_12), .Y (cout));
  CLKINVX1 g35(.A (n_9), .Y (n_11));
  NOR2X2 g34(.A (n_8), .B (cin), .Y (n_12));
  OAI21X1 g64(.A0 (n_14), .A1 (n_15), .B0 (n_16), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_14));
  DLY2X1 g1(.A (cin), .Y (n_15));
  NAND2X1 g65(.A (n_14), .B (n_15), .Y (n_16));
endmodule

module full_adder_80(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_10, n_11, n_12, n_16, n_20, n_21, n_23;
  OAI22XL g61__9945(.A0 (n_12), .A1 (b), .B0 (n_11), .B1 (a), .Y (n_4));
  XNOR2X1 g2__2883(.A (n_16), .B (n_4), .Y (sum));
  NAND2X2 g66(.A (b), .B (a), .Y (n_10));
  CLKINVX1 g68(.A (b), .Y (n_11));
  CLKINVX1 g69(.A (a), .Y (n_12));
  INVXL g70(.A (cin), .Y (n_16));
  NAND2X2 g20(.A (n_10), .B (n_21), .Y (cout));
  NAND2X2 g21(.A (n_20), .B (cin), .Y (n_21));
  CLKINVX2 g22(.A (n_23), .Y (n_20));
  AND2X1 g2(.A (n_11), .B (n_12), .Y (n_23));
endmodule

module full_adder_79(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_9, n_12, n_13, n_14, n_15, n_16;
  OAI22XL g61__1666(.A0 (n_14), .A1 (b), .B0 (n_13), .B1 (a), .Y (n_4));
  XNOR2X1 g2__7410(.A (n_9), .B (n_4), .Y (sum));
  INVXL fopt(.A (cin), .Y (n_9));
  NAND2X2 g63(.A (n_12), .B (n_16), .Y (cout));
  NAND2X2 g66(.A (b), .B (a), .Y (n_12));
  NAND2X2 g67(.A (n_15), .B (cin), .Y (n_16));
  NAND2X2 g68(.A (n_13), .B (n_14), .Y (n_15));
  CLKINVX1 g69(.A (b), .Y (n_13));
  CLKINVX1 g70(.A (a), .Y (n_14));
endmodule

module full_adder_78(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_11, n_12, n_13, n_17, n_18, n_25;
  NAND2X2 g64(.A (n_11), .B (n_13), .Y (cout));
  NAND2X2 g31(.A (a), .B (b), .Y (n_11));
  NAND2X2 g65(.A (n_12), .B (cin), .Y (n_13));
  OR2X4 g32(.A (b), .B (a), .Y (n_12));
  OAI21X1 g29(.A0 (n_25), .A1 (n_17), .B0 (n_18), .Y (sum));
  DLY2X1 g1(.A (cin), .Y (n_17));
  NAND2X1 g30(.A (n_25), .B (n_17), .Y (n_18));
  XNOR2X1 g2(.A (b), .B (a), .Y (n_25));
endmodule

module full_adder_77(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_10, n_11, n_12, n_13, n_14, n_16;
  OAI22XL g61__6260(.A0 (n_12), .A1 (b), .B0 (n_11), .B1 (a), .Y (n_4));
  XNOR2X1 g2__4319(.A (n_16), .B (n_4), .Y (sum));
  NAND2X2 g62(.A (n_10), .B (n_14), .Y (cout));
  NAND2X2 g66(.A (b), .B (a), .Y (n_10));
  NAND2X2 g63(.A (n_13), .B (cin), .Y (n_14));
  NAND2X2 g67(.A (n_11), .B (n_12), .Y (n_13));
  CLKINVX1 g68(.A (b), .Y (n_11));
  CLKINVX1 g69(.A (a), .Y (n_12));
  INVXL g70(.A (cin), .Y (n_16));
endmodule

module full_adder_76(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_11, n_12, n_13, n_15, n_16, n_17;
  NAND2X2 g64(.A (n_11), .B (n_13), .Y (cout));
  NAND2X2 g31(.A (a), .B (b), .Y (n_11));
  NAND2X2 g65(.A (n_12), .B (cin), .Y (n_13));
  OR2X4 g32(.A (b), .B (a), .Y (n_12));
  OAI21X1 g29(.A0 (n_15), .A1 (n_16), .B0 (n_17), .Y (sum));
  XNOR2X1 g66(.A (a), .B (b), .Y (n_15));
  DLY2X1 g1(.A (cin), .Y (n_16));
  NAND2X1 g30(.A (n_15), .B (n_16), .Y (n_17));
endmodule

module full_adder_75(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_10, n_11, n_12, n_16, n_20, n_21, n_23;
  OAI22XL g61__1617(.A0 (n_12), .A1 (b), .B0 (n_11), .B1 (a), .Y (n_4));
  XNOR2X1 g2__2802(.A (n_16), .B (n_4), .Y (sum));
  NAND2X2 g66(.A (b), .B (a), .Y (n_10));
  CLKINVX1 g68(.A (b), .Y (n_11));
  CLKINVX1 g69(.A (a), .Y (n_12));
  INVXL g70(.A (cin), .Y (n_16));
  NAND2X2 g20(.A (n_10), .B (n_21), .Y (cout));
  NAND2X2 g21(.A (n_20), .B (cin), .Y (n_21));
  CLKINVX1 g22(.A (n_23), .Y (n_20));
  AND2XL g2(.A (n_11), .B (n_12), .Y (n_23));
endmodule

module full_adder_74(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_7, n_8, n_10, n_11, n_17, n_18, n_19, n_20;
  AND2X1 g30(.A (a), .B (b), .Y (n_7));
  OR2X8 g29(.A (a), .B (b), .Y (n_8));
  NAND2X2 g27(.A (n_10), .B (n_11), .Y (cout));
  NAND2X2 g64(.A (n_7), .B (n_8), .Y (n_10));
  NAND2X2 g65(.A (n_8), .B (cin), .Y (n_11));
  OAI21X1 g37(.A0 (n_18), .A1 (n_19), .B0 (n_20), .Y (sum));
  OAI21X1 g39(.A0 (b), .A1 (a), .B0 (n_17), .Y (n_18));
  NAND2XL g40(.A (a), .B (b), .Y (n_17));
  DLY2X1 g68(.A (cin), .Y (n_19));
  NAND2X1 g38(.A (n_18), .B (n_19), .Y (n_20));
endmodule

module full_adder_73(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_11, n_12, n_13, n_15, n_16, n_17;
  NAND2X2 g64(.A (n_11), .B (n_13), .Y (cout));
  NAND2X2 g31(.A (a), .B (b), .Y (n_11));
  NAND2X2 g65(.A (n_12), .B (cin), .Y (n_13));
  OR2X4 g32(.A (b), .B (a), .Y (n_12));
  OAI21X1 g29(.A0 (n_15), .A1 (n_16), .B0 (n_17), .Y (sum));
  XNOR2X1 g66(.A (a), .B (b), .Y (n_15));
  DLY2X1 g1(.A (cin), .Y (n_16));
  NAND2X1 g30(.A (n_15), .B (n_16), .Y (n_17));
endmodule

module full_adder_72(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_12, n_13, n_14, n_16, n_17, n_18, n_19;
  NAND2X2 g53(.A (n_12), .B (n_14), .Y (cout));
  NAND2X2 g55(.A (a), .B (b), .Y (n_12));
  NAND2X2 g54(.A (n_13), .B (cin), .Y (n_14));
  OR2X4 g56(.A (b), .B (a), .Y (n_13));
  OAI21X1 g36(.A0 (n_17), .A1 (n_18), .B0 (n_19), .Y (sum));
  OAI21X1 g38(.A0 (b), .A1 (a), .B0 (n_16), .Y (n_17));
  NAND2XL g39(.A (a), .B (b), .Y (n_16));
  DLY2X1 g1(.A (cin), .Y (n_18));
  NAND2XL g37(.A (n_17), .B (n_18), .Y (n_19));
endmodule

module full_adder_71(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_10, n_11, n_12, n_18, n_19, n_20, n_21;
  NAND2X2 g64(.A (n_10), .B (n_12), .Y (cout));
  NAND2X2 g31(.A (a), .B (b), .Y (n_10));
  NAND2X2 g65(.A (n_11), .B (cin), .Y (n_12));
  OR2X4 g32(.A (b), .B (a), .Y (n_11));
  OAI21X1 g37(.A0 (n_19), .A1 (n_20), .B0 (n_21), .Y (sum));
  OAI21X1 g39(.A0 (b), .A1 (a), .B0 (n_18), .Y (n_19));
  NAND2XL g40(.A (a), .B (b), .Y (n_18));
  DLY2X1 g67(.A (cin), .Y (n_20));
  NAND2XL g38(.A (n_19), .B (n_20), .Y (n_21));
endmodule

module full_adder_70(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_9, n_10, n_11, n_12;
  MXI2XL g61__6417(.A (n_10), .B (b), .S0 (a), .Y (n_4));
  CLKXOR2X1 g2__5107(.A (cin), .B (n_4), .Y (sum));
  NAND2X2 g61(.A (n_9), .B (n_12), .Y (cout));
  NAND2X2 g63(.A (a), .B (b), .Y (n_9));
  NAND2X2 g62(.A (n_11), .B (cin), .Y (n_12));
  NAND2BX4 g64(.AN (a), .B (n_10), .Y (n_11));
  CLKINVX1 g66(.A (b), .Y (n_10));
endmodule

module full_adder_69(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_9, n_10, n_11, n_14;
  CLKXOR2X1 g2__6783(.A (cin), .B (n_14), .Y (sum));
  NAND2X2 g61(.A (n_9), .B (n_11), .Y (cout));
  NAND2X2 g63(.A (a), .B (b), .Y (n_9));
  NAND2X2 g62(.A (n_10), .B (cin), .Y (n_11));
  OR2X4 g64(.A (b), .B (a), .Y (n_10));
  CLKXOR2X1 g2(.A (b), .B (a), .Y (n_14));
endmodule

module full_adder_68(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_1, n_11, n_12, n_13;
  XNOR2X1 g62__1617(.A (a), .B (b), .Y (n_1));
  XNOR2X2 g2__2802(.A (cin), .B (n_1), .Y (sum));
  NAND2X2 g65(.A (n_11), .B (n_13), .Y (cout));
  NAND2X2 g31(.A (a), .B (b), .Y (n_11));
  NAND2X2 g66(.A (n_12), .B (cin), .Y (n_13));
  OR2X4 g32(.A (b), .B (a), .Y (n_12));
endmodule

module full_adder_67(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_23, n_24, n_27, n_29, n_30, n_31, n_32;
  OAI21X1 g32(.A0 (n_29), .A1 (n_31), .B0 (n_32), .Y (sum));
  NAND2X2 g57(.A (b), .B (a), .Y (n_23));
  OR2X4 g58(.A (a), .B (b), .Y (n_24));
  NAND2X2 g14(.A (n_23), .B (n_27), .Y (cout));
  NAND2X2 g15(.A (n_24), .B (cin), .Y (n_27));
  NAND2XL g20(.A (n_29), .B (n_31), .Y (n_32));
  CLKBUFX2 fopt(.A (cin), .Y (n_29));
  OAI21X1 g21(.A0 (b), .A1 (a), .B0 (n_30), .Y (n_31));
  NAND2XL g22(.A (a), .B (b), .Y (n_30));
endmodule

module full_adder_66(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_32, n_42, n_43, n_44, n_46, n_47, n_48;
  CLKINVX1 g66(.A (b), .Y (n_32));
  NAND2X2 g67(.A (n_42), .B (n_44), .Y (cout));
  NAND2X2 g68(.A (b), .B (a), .Y (n_42));
  NAND2X2 g69(.A (n_43), .B (cin), .Y (n_44));
  NAND2BX4 g27(.AN (a), .B (n_32), .Y (n_43));
  MXI2X1 g37(.A (n_46), .B (n_47), .S0 (n_48), .Y (sum));
  INVXL fopt40(.A (cin), .Y (n_46));
  CLKINVX1 fopt(.A (n_46), .Y (n_47));
  MXI2XL g38(.A (n_32), .B (b), .S0 (a), .Y (n_48));
endmodule

module full_adder_65(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_18, n_20, n_30, n_32, n_33;
  NOR2X2 g79(.A (a), .B (b), .Y (n_18));
  NAND2X4 g80(.A (a), .B (b), .Y (n_20));
  XNOR2X1 g35(.A (a), .B (b), .Y (n_30));
  NAND2X4 g20(.A (n_20), .B (n_33), .Y (cout));
  NAND2X2 g21(.A (n_32), .B (cin), .Y (n_33));
  CLKINVX1 g22(.A (n_18), .Y (n_32));
  XNOR2X2 g2(.A (cin), .B (n_30), .Y (sum));
endmodule

module full_adder_64(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_29, n_30, n_44, n_48, n_50, n_51;
  OAI21X1 g48(.A0 (a), .A1 (b), .B0 (n_50), .Y (n_29));
  CLKINVX1 g47(.A (n_29), .Y (n_30));
  OAI22X2 g27(.A0 (n_29), .A1 (cin), .B0 (n_30), .B1 (n_44), .Y (sum));
  INVX2 fopt(.A (cin), .Y (n_44));
  NAND2X2 g70(.A (n_50), .B (n_48), .Y (cout));
  NAND2X2 g1(.A (n_51), .B (cin), .Y (n_48));
  NAND2XL g73(.A (b), .B (a), .Y (n_50));
  OR2XL g74(.A (b), .B (a), .Y (n_51));
endmodule

module RCA64(A, B, cin, sum, cout);
  input [63:0] A, B;
  input cin;
  output [63:0] sum;
  output cout;
  wire [63:0] A, B;
  wire cin;
  wire [63:0] sum;
  wire cout;
  wire [64:0] c;
  full_adder \FA_CHAIN[0].fa (.a (A[0]), .b (B[0]), .cin (cin), .sum
       (sum[0]), .cout (c[1]));
  full_adder_126 \FA_CHAIN[1].fa (.a (A[1]), .b (B[1]), .cin (c[1]),
       .sum (sum[1]), .cout (c[2]));
  full_adder_125 \FA_CHAIN[2].fa (.a (A[2]), .b (B[2]), .cin (c[2]),
       .sum (sum[2]), .cout (c[3]));
  full_adder_124 \FA_CHAIN[3].fa (.a (A[3]), .b (B[3]), .cin (c[3]),
       .sum (sum[3]), .cout (c[4]));
  full_adder_123 \FA_CHAIN[4].fa (.a (A[4]), .b (B[4]), .cin (c[4]),
       .sum (sum[4]), .cout (c[5]));
  full_adder_122 \FA_CHAIN[5].fa (.a (A[5]), .b (B[5]), .cin (c[5]),
       .sum (sum[5]), .cout (c[6]));
  full_adder_121 \FA_CHAIN[6].fa (.a (A[6]), .b (B[6]), .cin (c[6]),
       .sum (sum[6]), .cout (c[7]));
  full_adder_120 \FA_CHAIN[7].fa (.a (A[7]), .b (B[7]), .cin (c[7]),
       .sum (sum[7]), .cout (c[8]));
  full_adder_119 \FA_CHAIN[8].fa (.a (A[8]), .b (B[8]), .cin (c[8]),
       .sum (sum[8]), .cout (c[9]));
  full_adder_118 \FA_CHAIN[9].fa (.a (A[9]), .b (B[9]), .cin (c[9]),
       .sum (sum[9]), .cout (c[10]));
  full_adder_117 \FA_CHAIN[10].fa (.a (A[10]), .b (B[10]), .cin
       (c[10]), .sum (sum[10]), .cout (c[11]));
  full_adder_116 \FA_CHAIN[11].fa (.a (A[11]), .b (B[11]), .cin
       (c[11]), .sum (sum[11]), .cout (c[12]));
  full_adder_115 \FA_CHAIN[12].fa (.a (A[12]), .b (B[12]), .cin
       (c[12]), .sum (sum[12]), .cout (c[13]));
  full_adder_114 \FA_CHAIN[13].fa (.a (A[13]), .b (B[13]), .cin
       (c[13]), .sum (sum[13]), .cout (c[14]));
  full_adder_113 \FA_CHAIN[14].fa (.a (A[14]), .b (B[14]), .cin
       (c[14]), .sum (sum[14]), .cout (c[15]));
  full_adder_112 \FA_CHAIN[15].fa (.a (A[15]), .b (B[15]), .cin
       (c[15]), .sum (sum[15]), .cout (c[16]));
  full_adder_111 \FA_CHAIN[16].fa (.a (A[16]), .b (B[16]), .cin
       (c[16]), .sum (sum[16]), .cout (c[17]));
  full_adder_110 \FA_CHAIN[17].fa (.a (A[17]), .b (B[17]), .cin
       (c[17]), .sum (sum[17]), .cout (c[18]));
  full_adder_109 \FA_CHAIN[18].fa (.a (A[18]), .b (B[18]), .cin
       (c[18]), .sum (sum[18]), .cout (c[19]));
  full_adder_108 \FA_CHAIN[19].fa (.a (A[19]), .b (B[19]), .cin
       (c[19]), .sum (sum[19]), .cout (c[20]));
  full_adder_107 \FA_CHAIN[20].fa (.a (A[20]), .b (B[20]), .cin
       (c[20]), .sum (sum[20]), .cout (c[21]));
  full_adder_106 \FA_CHAIN[21].fa (.a (A[21]), .b (B[21]), .cin
       (c[21]), .sum (sum[21]), .cout (c[22]));
  full_adder_105 \FA_CHAIN[22].fa (.a (A[22]), .b (B[22]), .cin
       (c[22]), .sum (sum[22]), .cout (c[23]));
  full_adder_104 \FA_CHAIN[23].fa (.a (A[23]), .b (B[23]), .cin
       (c[23]), .sum (sum[23]), .cout (c[24]));
  full_adder_103 \FA_CHAIN[24].fa (.a (A[24]), .b (B[24]), .cin
       (c[24]), .sum (sum[24]), .cout (c[25]));
  full_adder_102 \FA_CHAIN[25].fa (.a (A[25]), .b (B[25]), .cin
       (c[25]), .sum (sum[25]), .cout (c[26]));
  full_adder_101 \FA_CHAIN[26].fa (.a (A[26]), .b (B[26]), .cin
       (c[26]), .sum (sum[26]), .cout (c[27]));
  full_adder_100 \FA_CHAIN[27].fa (.a (A[27]), .b (B[27]), .cin
       (c[27]), .sum (sum[27]), .cout (c[28]));
  full_adder_99 \FA_CHAIN[28].fa (.a (A[28]), .b (B[28]), .cin (c[28]),
       .sum (sum[28]), .cout (c[29]));
  full_adder_98 \FA_CHAIN[29].fa (.a (A[29]), .b (B[29]), .cin (c[29]),
       .sum (sum[29]), .cout (c[30]));
  full_adder_97 \FA_CHAIN[30].fa (.a (A[30]), .b (B[30]), .cin (c[30]),
       .sum (sum[30]), .cout (c[31]));
  full_adder_96 \FA_CHAIN[31].fa (.a (A[31]), .b (B[31]), .cin (c[31]),
       .sum (sum[31]), .cout (c[32]));
  full_adder_95 \FA_CHAIN[32].fa (.a (A[32]), .b (B[32]), .cin (c[32]),
       .sum (sum[32]), .cout (c[33]));
  full_adder_94 \FA_CHAIN[33].fa (.a (A[33]), .b (B[33]), .cin (c[33]),
       .sum (sum[33]), .cout (c[34]));
  full_adder_93 \FA_CHAIN[34].fa (.a (A[34]), .b (B[34]), .cin (c[34]),
       .sum (sum[34]), .cout (c[35]));
  full_adder_92 \FA_CHAIN[35].fa (.a (A[35]), .b (B[35]), .cin (c[35]),
       .sum (sum[35]), .cout (c[36]));
  full_adder_91 \FA_CHAIN[36].fa (.a (A[36]), .b (B[36]), .cin (c[36]),
       .sum (sum[36]), .cout (c[37]));
  full_adder_90 \FA_CHAIN[37].fa (.a (A[37]), .b (B[37]), .cin (c[37]),
       .sum (sum[37]), .cout (c[38]));
  full_adder_89 \FA_CHAIN[38].fa (.a (A[38]), .b (B[38]), .cin (c[38]),
       .sum (sum[38]), .cout (c[39]));
  full_adder_88 \FA_CHAIN[39].fa (.a (A[39]), .b (B[39]), .cin (c[39]),
       .sum (sum[39]), .cout (c[40]));
  full_adder_87 \FA_CHAIN[40].fa (.a (A[40]), .b (B[40]), .cin (c[40]),
       .sum (sum[40]), .cout (c[41]));
  full_adder_86 \FA_CHAIN[41].fa (.a (A[41]), .b (B[41]), .cin (c[41]),
       .sum (sum[41]), .cout (c[42]));
  full_adder_85 \FA_CHAIN[42].fa (.a (A[42]), .b (B[42]), .cin (c[42]),
       .sum (sum[42]), .cout (c[43]));
  full_adder_84 \FA_CHAIN[43].fa (.a (A[43]), .b (B[43]), .cin (c[43]),
       .sum (sum[43]), .cout (c[44]));
  full_adder_83 \FA_CHAIN[44].fa (.a (A[44]), .b (B[44]), .cin (c[44]),
       .sum (sum[44]), .cout (c[45]));
  full_adder_82 \FA_CHAIN[45].fa (.a (A[45]), .b (B[45]), .cin (c[45]),
       .sum (sum[45]), .cout (c[46]));
  full_adder_81 \FA_CHAIN[46].fa (.a (A[46]), .b (B[46]), .cin (c[46]),
       .sum (sum[46]), .cout (c[47]));
  full_adder_80 \FA_CHAIN[47].fa (.a (A[47]), .b (B[47]), .cin (c[47]),
       .sum (sum[47]), .cout (c[48]));
  full_adder_79 \FA_CHAIN[48].fa (.a (A[48]), .b (B[48]), .cin (c[48]),
       .sum (sum[48]), .cout (c[49]));
  full_adder_78 \FA_CHAIN[49].fa (.a (A[49]), .b (B[49]), .cin (c[49]),
       .sum (sum[49]), .cout (c[50]));
  full_adder_77 \FA_CHAIN[50].fa (.a (A[50]), .b (B[50]), .cin (c[50]),
       .sum (sum[50]), .cout (c[51]));
  full_adder_76 \FA_CHAIN[51].fa (.a (A[51]), .b (B[51]), .cin (c[51]),
       .sum (sum[51]), .cout (c[52]));
  full_adder_75 \FA_CHAIN[52].fa (.a (A[52]), .b (B[52]), .cin (c[52]),
       .sum (sum[52]), .cout (c[53]));
  full_adder_74 \FA_CHAIN[53].fa (.a (A[53]), .b (B[53]), .cin (c[53]),
       .sum (sum[53]), .cout (c[54]));
  full_adder_73 \FA_CHAIN[54].fa (.a (A[54]), .b (B[54]), .cin (c[54]),
       .sum (sum[54]), .cout (c[55]));
  full_adder_72 \FA_CHAIN[55].fa (.a (A[55]), .b (B[55]), .cin (c[55]),
       .sum (sum[55]), .cout (c[56]));
  full_adder_71 \FA_CHAIN[56].fa (.a (A[56]), .b (B[56]), .cin (c[56]),
       .sum (sum[56]), .cout (c[57]));
  full_adder_70 \FA_CHAIN[57].fa (.a (A[57]), .b (B[57]), .cin (c[57]),
       .sum (sum[57]), .cout (c[58]));
  full_adder_69 \FA_CHAIN[58].fa (.a (A[58]), .b (B[58]), .cin (c[58]),
       .sum (sum[58]), .cout (c[59]));
  full_adder_68 \FA_CHAIN[59].fa (.a (A[59]), .b (B[59]), .cin (c[59]),
       .sum (sum[59]), .cout (c[60]));
  full_adder_67 \FA_CHAIN[60].fa (.a (A[60]), .b (B[60]), .cin (c[60]),
       .sum (sum[60]), .cout (c[61]));
  full_adder_66 \FA_CHAIN[61].fa (.a (A[61]), .b (B[61]), .cin (c[61]),
       .sum (sum[61]), .cout (c[62]));
  full_adder_65 \FA_CHAIN[62].fa (.a (A[62]), .b (B[62]), .cin (c[62]),
       .sum (sum[62]), .cout (c[63]));
  full_adder_64 \FA_CHAIN[63].fa (.a (A[63]), .b (B[63]), .cin (c[63]),
       .sum (sum[63]), .cout (cout));
endmodule

