
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr 13 2026 21:58:25 IST (Apr 13 2026 16:28:25 UTC)

// Verification Directory fv/RCA32 

module full_adder(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_1, n_2, n_7, n_40, n_41, n_42, n_44;
  OAI21X1 g71__2398(.A0 (n_1), .A1 (n_44), .B0 (n_7), .Y (sum));
  NAND2XL g72__5107(.A (n_1), .B (n_44), .Y (n_7));
  DLY2X1 fopt(.A (a), .Y (n_2));
  DLY2X1 fopt79(.A (cin), .Y (n_1));
  OAI21X2 g74(.A0 (n_40), .A1 (n_41), .B0 (n_42), .Y (cout));
  CLKINVX1 g78(.A (b), .Y (n_40));
  NOR2X2 g77(.A (a), .B (cin), .Y (n_41));
  NAND2X1 g76(.A (a), .B (cin), .Y (n_42));
  MXI2XL g75(.A (b), .B (n_40), .S0 (n_2), .Y (n_44));
endmodule

module full_adder_62(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_5, n_10, n_17, n_18, n_19, n_20;
  OAI21X1 g63__6783(.A0 (n_10), .A1 (n_0), .B0 (n_5), .Y (sum));
  NAND2XL g64__3680(.A (n_10), .B (n_0), .Y (n_5));
  CLKXOR2X1 g2__5122(.A (n_18), .B (a), .Y (n_0));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NAND2X2 g27(.A (n_17), .B (n_20), .Y (cout));
  NAND2X1 g29(.A (b), .B (a), .Y (n_17));
  NAND2X2 g28(.A (n_19), .B (cin), .Y (n_20));
  NAND2BX2 g30(.AN (a), .B (n_18), .Y (n_19));
  CLKINVX1 g31(.A (b), .Y (n_18));
endmodule

module full_adder_61(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_1, n_4, n_61, n_62, n_63;
  OAI21X1 g59__8246(.A0 (n_0), .A1 (n_1), .B0 (n_4), .Y (sum));
  NAND2XL g60__7098(.A (n_0), .B (n_1), .Y (n_4));
  XNOR2XL g63__1881(.A (a), .B (b), .Y (n_1));
  DLY2X1 fopt(.A (cin), .Y (n_0));
  CLKINVX2 fopt64(.A (n_63), .Y (cout));
  OAI21X2 g21(.A0 (n_61), .A1 (cin), .B0 (n_62), .Y (n_63));
  CLKAND2X2 g23(.A (b), .B (a), .Y (n_61));
  OR2X2 g22(.A (b), .B (a), .Y (n_62));
endmodule

module full_adder_60(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_5, n_10, n_13, n_14, n_15, n_16, n_19;
  wire n_22, n_23;
  OAI21X1 g59__5115(.A0 (n_10), .A1 (n_0), .B0 (n_5), .Y (sum));
  NAND2XL g60__7482(.A (n_10), .B (n_0), .Y (n_5));
  XNOR2XL g2__6161(.A (n_15), .B (n_14), .Y (n_0));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NAND2X2 g64(.A (b), .B (a), .Y (n_13));
  NAND2XL g68(.A (n_14), .B (n_15), .Y (n_16));
  CLKINVX1 g69(.A (b), .Y (n_14));
  CLKINVX1 g66(.A (a), .Y (n_15));
  CLKINVX1 g16(.A (n_16), .Y (n_19));
  NAND2X2 g20(.A (n_13), .B (n_23), .Y (cout));
  NAND2X2 g21(.A (n_22), .B (cin), .Y (n_23));
  CLKINVX2 g22(.A (n_19), .Y (n_22));
endmodule

module full_adder_59(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_1, n_4, n_10, n_11, n_61, n_62;
  OAI21X1 g59__9315(.A0 (n_0), .A1 (n_1), .B0 (n_4), .Y (sum));
  NAND2XL g60__9945(.A (n_0), .B (n_1), .Y (n_4));
  XNOR2XL g63__2346(.A (a), .B (b), .Y (n_1));
  DLY2X1 fopt(.A (cin), .Y (n_0));
  CLKAND2X2 g30(.A (a), .B (b), .Y (n_10));
  OR2X1 g29(.A (a), .B (b), .Y (n_11));
  NOR2X2 g33(.A (n_61), .B (n_62), .Y (cout));
  CLKINVX1 g35(.A (n_11), .Y (n_61));
  NOR2X2 g34(.A (n_10), .B (cin), .Y (n_62));
endmodule

module full_adder_58(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_6, n_11, n_14, n_15, n_16, n_17, n_20;
  wire n_23, n_24;
  OAI21X1 g59__1666(.A0 (n_11), .A1 (n_0), .B0 (n_6), .Y (sum));
  NAND2XL g60__7410(.A (n_11), .B (n_0), .Y (n_6));
  XNOR2XL g2__5477(.A (n_16), .B (n_15), .Y (n_0));
  DLY2X1 fopt(.A (cin), .Y (n_11));
  NAND2X4 g64(.A (b), .B (a), .Y (n_14));
  NAND2XL g65(.A (n_15), .B (n_16), .Y (n_17));
  CLKINVX1 g70(.A (b), .Y (n_15));
  CLKINVX1 g66(.A (a), .Y (n_16));
  CLKINVX1 g16(.A (n_17), .Y (n_20));
  NAND2X2 g20(.A (n_14), .B (n_24), .Y (cout));
  NAND2X2 g21(.A (n_23), .B (cin), .Y (n_24));
  CLKINVX2 g22(.A (n_20), .Y (n_23));
endmodule

module full_adder_57(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_1, n_10, n_11, n_61, n_62;
  XNOR2XL g63__4319(.A (a), .B (b), .Y (n_1));
  DLY2X1 fopt(.A (cin), .Y (n_0));
  CLKAND2X2 g30(.A (a), .B (b), .Y (n_10));
  OR2X1 g29(.A (a), .B (b), .Y (n_11));
  NOR2X2 g33(.A (n_61), .B (n_62), .Y (cout));
  CLKINVX1 g35(.A (n_11), .Y (n_61));
  NOR2X2 g34(.A (n_10), .B (cin), .Y (n_62));
  XNOR2X1 g2(.A (n_0), .B (n_1), .Y (sum));
endmodule

module full_adder_56(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_5, n_10, n_12, n_13, n_14, n_17;
  OAI21X1 g59__8428(.A0 (n_10), .A1 (n_17), .B0 (n_5), .Y (sum));
  NAND2XL g60__5526(.A (n_10), .B (n_17), .Y (n_5));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NAND2X2 g61(.A (n_12), .B (n_14), .Y (cout));
  NAND2X4 g63(.A (a), .B (b), .Y (n_12));
  NAND2X2 g62(.A (n_13), .B (cin), .Y (n_14));
  OR2X6 g64(.A (b), .B (a), .Y (n_13));
  XNOR2X1 g2(.A (b), .B (a), .Y (n_17));
endmodule

module full_adder_55(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_1, n_3, n_10, n_11, n_12;
  OAI21X1 g60__1705(.A0 (n_0), .A1 (n_1), .B0 (n_3), .Y (sum));
  NAND2X1 g61__5122(.A (n_0), .B (n_1), .Y (n_3));
  XNOR2X1 g63__7098(.A (a), .B (b), .Y (n_1));
  DLY2X1 fopt(.A (cin), .Y (n_0));
  CLKINVX2 fopt65(.A (n_12), .Y (cout));
  OAI21X2 g28(.A0 (n_10), .A1 (cin), .B0 (n_11), .Y (n_12));
  CLKAND2X2 g30(.A (a), .B (b), .Y (n_10));
  OR2X2 g29(.A (a), .B (b), .Y (n_11));
endmodule

module full_adder_54(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_5, n_10, n_24, n_25, n_26, n_31;
  OAI21X1 g59__6131(.A0 (n_10), .A1 (n_31), .B0 (n_5), .Y (sum));
  NAND2X1 g60__1881(.A (n_10), .B (n_31), .Y (n_5));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NAND2X2 g68(.A (n_24), .B (n_26), .Y (cout));
  NAND2X2 g69(.A (b), .B (a), .Y (n_24));
  NAND2X2 g70(.A (n_25), .B (cin), .Y (n_26));
  OR2X6 g71(.A (a), .B (b), .Y (n_25));
  XNOR2X1 g2(.A (b), .B (a), .Y (n_31));
endmodule

module full_adder_53(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_5, n_10, n_12, n_13, n_17, n_18, n_25;
  OAI21X1 g59__9315(.A0 (n_10), .A1 (n_25), .B0 (n_5), .Y (sum));
  NAND2X1 g60__9945(.A (n_10), .B (n_25), .Y (n_5));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NAND2X2 g63(.A (a), .B (b), .Y (n_12));
  NOR2XL g64(.A (a), .B (b), .Y (n_13));
  NAND2X2 g12(.A (n_12), .B (n_18), .Y (cout));
  NAND2X2 g13(.A (n_17), .B (cin), .Y (n_18));
  CLKINVX1 g14(.A (n_13), .Y (n_17));
  XNOR2X1 g2(.A (b), .B (a), .Y (n_25));
endmodule

module full_adder_52(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_2, n_4, n_10, n_11, n_12;
  OAI21X1 g60__6417(.A0 (n_0), .A1 (n_2), .B0 (n_4), .Y (sum));
  NAND2X1 g61__5477(.A (n_0), .B (n_2), .Y (n_4));
  XNOR2X1 g63__5107(.A (a), .B (b), .Y (n_2));
  DLY2X1 fopt64(.A (cin), .Y (n_0));
  CLKINVX2 fopt1(.A (n_12), .Y (cout));
  OAI21X2 g28(.A0 (n_10), .A1 (cin), .B0 (n_11), .Y (n_12));
  CLKAND2X2 g30(.A (a), .B (b), .Y (n_10));
  OR2X2 g29(.A (a), .B (b), .Y (n_11));
endmodule

module full_adder_51(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_5, n_10, n_17, n_18, n_19, n_24;
  OAI21X1 g59__6260(.A0 (n_10), .A1 (n_24), .B0 (n_5), .Y (sum));
  NAND2X1 g60__4319(.A (n_10), .B (n_24), .Y (n_5));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NAND2X2 g22(.A (n_17), .B (n_19), .Y (cout));
  NAND2X2 g24(.A (b), .B (a), .Y (n_17));
  NAND2X2 g23(.A (n_18), .B (cin), .Y (n_19));
  OR2X6 g25(.A (a), .B (b), .Y (n_18));
  XNOR2X1 g2(.A (b), .B (a), .Y (n_24));
endmodule

module full_adder_50(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_5, n_10, n_12, n_14, n_17, n_18, n_25;
  OAI21X1 g59__1617(.A0 (n_10), .A1 (n_25), .B0 (n_5), .Y (sum));
  NAND2X1 g60__2802(.A (n_10), .B (n_25), .Y (n_5));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NOR2XL g63(.A (a), .B (b), .Y (n_12));
  NAND2X2 g62(.A (a), .B (b), .Y (n_14));
  NAND2X2 g20(.A (n_14), .B (n_18), .Y (cout));
  NAND2X2 g21(.A (n_17), .B (cin), .Y (n_18));
  CLKINVX1 g22(.A (n_12), .Y (n_17));
  XNOR2X1 g2(.A (b), .B (a), .Y (n_25));
endmodule

module full_adder_49(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_8, n_9, n_10, n_39, n_40, n_41;
  INVX2 fopt(.A (n_10), .Y (cout));
  OAI21X2 g28(.A0 (n_8), .A1 (cin), .B0 (n_9), .Y (n_10));
  CLKAND2X2 g30(.A (a), .B (b), .Y (n_8));
  OR2X2 g29(.A (a), .B (b), .Y (n_9));
  OAI21X1 g64(.A0 (n_39), .A1 (n_40), .B0 (n_41), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_39));
  DLY2X1 g1(.A (cin), .Y (n_40));
  NAND2X1 g65(.A (n_39), .B (n_40), .Y (n_41));
endmodule

module full_adder_48(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_10, n_11, n_12, n_16, n_20, n_21, n_23;
  OAI22XL g61__4733(.A0 (n_12), .A1 (b), .B0 (n_11), .B1 (a), .Y (n_4));
  XNOR2X1 g2__6161(.A (n_16), .B (n_4), .Y (sum));
  NAND2X4 g66(.A (b), .B (a), .Y (n_10));
  CLKINVX1 g68(.A (b), .Y (n_11));
  CLKINVX1 g69(.A (a), .Y (n_12));
  INVXL g70(.A (cin), .Y (n_16));
  NAND2X2 g20(.A (n_10), .B (n_21), .Y (cout));
  NAND2X2 g21(.A (n_20), .B (cin), .Y (n_21));
  CLKINVX2 g22(.A (n_23), .Y (n_20));
  AND2X1 g2(.A (n_11), .B (n_12), .Y (n_23));
endmodule

module full_adder_47(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_8, n_9, n_10, n_13, n_14, n_16;
  INVX2 fopt(.A (n_10), .Y (cout));
  OAI21X2 g28(.A0 (n_8), .A1 (cin), .B0 (n_9), .Y (n_10));
  CLKAND2X2 g30(.A (a), .B (b), .Y (n_8));
  OR2X1 g29(.A (a), .B (b), .Y (n_9));
  OAI21X1 g64(.A0 (n_16), .A1 (n_13), .B0 (n_14), .Y (sum));
  DLY2X1 g1(.A (cin), .Y (n_13));
  NAND2X1 g65(.A (n_16), .B (n_13), .Y (n_14));
  XNOR2X1 g2(.A (b), .B (a), .Y (n_16));
endmodule

module full_adder_46(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_4, n_10, n_11, n_12, n_13, n_16, n_17, n_20;
  wire n_21;
  OAI22XL g61__1666(.A0 (n_12), .A1 (b), .B0 (n_11), .B1 (a), .Y (n_4));
  XNOR2X1 g2__7410(.A (n_16), .B (n_4), .Y (sum));
  NAND2X4 g66(.A (b), .B (a), .Y (n_10));
  NAND2XL g67(.A (n_11), .B (n_12), .Y (n_13));
  CLKINVX1 g68(.A (b), .Y (n_11));
  CLKINVX1 g69(.A (a), .Y (n_12));
  INVXL g70(.A (cin), .Y (n_16));
  CLKINVX1 g16(.A (n_13), .Y (n_17));
  NAND2X4 g20(.A (n_10), .B (n_21), .Y (cout));
  NAND2X4 g21(.A (n_20), .B (cin), .Y (n_21));
  CLKINVX2 g22(.A (n_17), .Y (n_20));
endmodule

module full_adder_45(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_11, n_12, n_13, n_15, n_16, n_17;
  NOR2X4 g37(.A (n_11), .B (n_13), .Y (cout));
  NOR2X6 g39(.A (a), .B (b), .Y (n_11));
  NOR2X4 g38(.A (n_12), .B (cin), .Y (n_13));
  CLKAND2X2 g67(.A (b), .B (a), .Y (n_12));
  OAI21X1 g29(.A0 (n_15), .A1 (n_16), .B0 (n_17), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_15));
  DLY2X1 g1(.A (cin), .Y (n_16));
  NAND2X1 g30(.A (n_15), .B (n_16), .Y (n_17));
endmodule

module full_adder_44(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_8, n_9, n_14, n_15, n_16, n_18;
  NAND2X4 g55(.A (a), .B (b), .Y (n_8));
  OR2X6 g56(.A (b), .B (a), .Y (n_9));
  OAI21X1 g29(.A0 (n_14), .A1 (n_15), .B0 (n_16), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_14));
  DLY2X1 g1(.A (cin), .Y (n_15));
  NAND2X1 g30(.A (n_14), .B (n_15), .Y (n_16));
  NAND2X4 g65(.A (n_8), .B (n_18), .Y (cout));
  NAND2X4 g66(.A (n_9), .B (cin), .Y (n_18));
endmodule

module full_adder_43(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_9, n_10, n_14, n_15, n_18, n_22;
  NAND2X2 g63(.A (a), .B (b), .Y (n_9));
  NOR2XL g64(.A (a), .B (b), .Y (n_10));
  NAND2X2 g12(.A (n_9), .B (n_15), .Y (cout));
  NAND2X2 g13(.A (n_14), .B (cin), .Y (n_15));
  CLKINVX2 g14(.A (n_10), .Y (n_14));
  CLKXOR2X1 g34(.A (n_22), .B (n_18), .Y (sum));
  DLY2X1 g1(.A (cin), .Y (n_18));
  XOR2XL g2(.A (b), .B (a), .Y (n_22));
endmodule

module full_adder_42(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_8, n_9, n_12, n_15, n_16, n_18, n_19, n_20;
  NOR2XL g62(.A (b), .B (a), .Y (n_8));
  INVXL g26(.A (n_8), .Y (n_12));
  NOR2X2 g23(.A (n_15), .B (n_16), .Y (cout));
  CLKINVX1 g64(.A (n_12), .Y (n_15));
  NOR2X2 g65(.A (n_9), .B (cin), .Y (n_16));
  OAI21X1 g29(.A0 (n_18), .A1 (n_19), .B0 (n_20), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_18));
  DLY2X1 g1(.A (cin), .Y (n_19));
  NAND2X1 g30(.A (n_18), .B (n_19), .Y (n_20));
  CLKAND2X2 g69(.A (a), .B (b), .Y (n_9));
endmodule

module full_adder_41(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_5, n_10, n_19, n_20, n_21, n_26;
  OAI21X1 g59__6131(.A0 (n_10), .A1 (n_26), .B0 (n_5), .Y (sum));
  NAND2X1 g60__1881(.A (n_10), .B (n_26), .Y (n_5));
  DLY2X1 fopt(.A (cin), .Y (n_10));
  NAND2X2 g22(.A (n_19), .B (n_21), .Y (cout));
  NAND2X4 g24(.A (a), .B (b), .Y (n_19));
  NAND2X2 g23(.A (n_20), .B (cin), .Y (n_21));
  OR2X1 g25(.A (b), .B (a), .Y (n_20));
  XNOR2X1 g2(.A (b), .B (a), .Y (n_26));
endmodule

module full_adder_40(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_14, n_15, n_16, n_19, n_21;
  NAND2X2 g22(.A (n_14), .B (n_16), .Y (cout));
  NAND2X2 g24(.A (b), .B (a), .Y (n_14));
  NAND2X2 g23(.A (n_15), .B (cin), .Y (n_16));
  OR2X4 g25(.A (a), .B (b), .Y (n_15));
  CLKXOR2X1 g34(.A (n_21), .B (n_19), .Y (sum));
  DLY2X1 g1(.A (cin), .Y (n_19));
  XOR2XL g2(.A (b), .B (a), .Y (n_21));
endmodule

module full_adder_39(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_10, n_11, n_14, n_17, n_18, n_20, n_21, n_22;
  NOR2XL g39(.A (a), .B (b), .Y (n_10));
  AND2X1 g40(.A (b), .B (a), .Y (n_11));
  INVXL g26(.A (n_10), .Y (n_14));
  NOR2X2 g23(.A (n_17), .B (n_18), .Y (cout));
  CLKINVX1 g64(.A (n_14), .Y (n_17));
  NOR2X2 g65(.A (n_11), .B (cin), .Y (n_18));
  OAI21X1 g29(.A0 (n_20), .A1 (n_21), .B0 (n_22), .Y (sum));
  XNOR2X1 g31(.A (a), .B (b), .Y (n_20));
  DLY2X1 g1(.A (cin), .Y (n_21));
  NAND2X1 g30(.A (n_20), .B (n_21), .Y (n_22));
endmodule

module full_adder_38(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_17, n_21, n_22, n_23;
  CLKXOR2X1 g2__8428(.A (cin), .B (n_21), .Y (sum));
  NAND2X4 g24(.A (a), .B (b), .Y (n_17));
  CLKXOR2X1 g2(.A (b), .B (a), .Y (n_21));
  NAND2X2 g15(.A (n_17), .B (n_23), .Y (cout));
  NAND2X2 g16(.A (n_22), .B (cin), .Y (n_23));
  OR2X1 g17(.A (a), .B (b), .Y (n_22));
endmodule

module full_adder_37(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_14, n_15, n_16, n_19;
  CLKXOR2X1 g2__2802(.A (cin), .B (n_19), .Y (sum));
  NAND2X2 g26(.A (n_14), .B (n_16), .Y (cout));
  NAND2X2 g28(.A (a), .B (b), .Y (n_14));
  NAND2X2 g27(.A (n_15), .B (cin), .Y (n_16));
  OR2X4 g29(.A (b), .B (a), .Y (n_15));
  CLKXOR2X1 g2(.A (b), .B (a), .Y (n_19));
endmodule

module full_adder_36(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_1, n_11, n_12, n_15, n_18, n_19;
  XNOR2X1 g62__5122(.A (a), .B (b), .Y (n_1));
  XNOR2X2 g2__8246(.A (cin), .B (n_1), .Y (sum));
  NOR2XL g39(.A (a), .B (b), .Y (n_11));
  AND2X1 g40(.A (b), .B (a), .Y (n_12));
  INVXL g26(.A (n_11), .Y (n_15));
  NOR2X2 g23(.A (n_18), .B (n_19), .Y (cout));
  CLKINVX1 g65(.A (n_15), .Y (n_18));
  NOR2X2 g66(.A (n_12), .B (cin), .Y (n_19));
endmodule

module full_adder_35(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_20, n_21, n_23, n_24, n_25, n_31, n_34;
  AND2X1 g30(.A (a), .B (b), .Y (n_20));
  OR2X1 g29(.A (a), .B (b), .Y (n_21));
  OAI21X1 g32(.A0 (n_23), .A1 (n_24), .B0 (n_25), .Y (sum));
  CLKBUFX2 fopt68(.A (cin), .Y (n_23));
  XNOR2X1 g34(.A (a), .B (b), .Y (n_24));
  NAND2X1 g33(.A (n_23), .B (n_24), .Y (n_25));
  CLKINVX1 g35(.A (n_21), .Y (n_31));
  NOR2X2 g24(.A (n_31), .B (n_34), .Y (cout));
  NOR2X2 g25(.A (n_20), .B (cin), .Y (n_34));
endmodule

module full_adder_34(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_34, n_35, n_36, n_39, n_41, n_46;
  NAND2X2 g63(.A (a), .B (b), .Y (n_34));
  NAND2BX2 g64(.AN (a), .B (n_35), .Y (n_36));
  CLKINVX1 g66(.A (b), .Y (n_35));
  NAND2X2 g14(.A (n_34), .B (n_39), .Y (cout));
  NAND2X2 g15(.A (n_36), .B (cin), .Y (n_39));
  INVXL fopt40(.A (cin), .Y (n_41));
  XNOR2X1 g2(.A (n_46), .B (n_41), .Y (sum));
  MXI2XL g3(.A (n_35), .B (b), .S0 (a), .Y (n_46));
endmodule

module full_adder_33(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_12, n_14, n_15, n_16, n_17, n_27;
  INVXL fopt2(.A (cin), .Y (n_12));
  NAND2X4 g61(.A (n_14), .B (n_17), .Y (cout));
  NAND2X4 g63(.A (a), .B (b), .Y (n_14));
  NAND2X2 g62(.A (n_16), .B (cin), .Y (n_17));
  NAND2BX4 g64(.AN (a), .B (n_15), .Y (n_16));
  CLKINVX1 g66(.A (b), .Y (n_15));
  XNOR2X1 g2(.A (n_27), .B (n_12), .Y (sum));
  MX2X1 g3(.A (b), .B (n_15), .S0 (a), .Y (n_27));
endmodule

module full_adder_32(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_20, n_21, n_22, n_25, n_29, n_31;
  OAI22X2 g33(.A0 (n_20), .A1 (cin), .B0 (n_21), .B1 (n_22), .Y (sum));
  OAI21X1 g35(.A0 (a), .A1 (b), .B0 (n_31), .Y (n_20));
  CLKINVX1 g34(.A (n_20), .Y (n_21));
  CLKINVX2 g37(.A (cin), .Y (n_22));
  OR2X1 g23(.A (a), .B (b), .Y (n_25));
  NAND2X2 g19(.A (n_31), .B (n_29), .Y (cout));
  NAND2X2 g70(.A (n_25), .B (cin), .Y (n_29));
  NAND2XL g71(.A (b), .B (a), .Y (n_31));
endmodule

module RCA32(A, B, cin, sum, cout);
  input [31:0] A, B;
  input cin;
  output [31:0] sum;
  output cout;
  wire [31:0] A, B;
  wire cin;
  wire [31:0] sum;
  wire cout;
  wire [32:0] c;
  full_adder \FA_CHAIN[0].fa (.a (A[0]), .b (B[0]), .cin (cin), .sum
       (sum[0]), .cout (c[1]));
  full_adder_62 \FA_CHAIN[1].fa (.a (A[1]), .b (B[1]), .cin (c[1]),
       .sum (sum[1]), .cout (c[2]));
  full_adder_61 \FA_CHAIN[2].fa (.a (A[2]), .b (B[2]), .cin (c[2]),
       .sum (sum[2]), .cout (c[3]));
  full_adder_60 \FA_CHAIN[3].fa (.a (A[3]), .b (B[3]), .cin (c[3]),
       .sum (sum[3]), .cout (c[4]));
  full_adder_59 \FA_CHAIN[4].fa (.a (A[4]), .b (B[4]), .cin (c[4]),
       .sum (sum[4]), .cout (c[5]));
  full_adder_58 \FA_CHAIN[5].fa (.a (A[5]), .b (B[5]), .cin (c[5]),
       .sum (sum[5]), .cout (c[6]));
  full_adder_57 \FA_CHAIN[6].fa (.a (A[6]), .b (B[6]), .cin (c[6]),
       .sum (sum[6]), .cout (c[7]));
  full_adder_56 \FA_CHAIN[7].fa (.a (A[7]), .b (B[7]), .cin (c[7]),
       .sum (sum[7]), .cout (c[8]));
  full_adder_55 \FA_CHAIN[8].fa (.a (A[8]), .b (B[8]), .cin (c[8]),
       .sum (sum[8]), .cout (c[9]));
  full_adder_54 \FA_CHAIN[9].fa (.a (A[9]), .b (B[9]), .cin (c[9]),
       .sum (sum[9]), .cout (c[10]));
  full_adder_53 \FA_CHAIN[10].fa (.a (A[10]), .b (B[10]), .cin (c[10]),
       .sum (sum[10]), .cout (c[11]));
  full_adder_52 \FA_CHAIN[11].fa (.a (A[11]), .b (B[11]), .cin (c[11]),
       .sum (sum[11]), .cout (c[12]));
  full_adder_51 \FA_CHAIN[12].fa (.a (A[12]), .b (B[12]), .cin (c[12]),
       .sum (sum[12]), .cout (c[13]));
  full_adder_50 \FA_CHAIN[13].fa (.a (A[13]), .b (B[13]), .cin (c[13]),
       .sum (sum[13]), .cout (c[14]));
  full_adder_49 \FA_CHAIN[14].fa (.a (A[14]), .b (B[14]), .cin (c[14]),
       .sum (sum[14]), .cout (c[15]));
  full_adder_48 \FA_CHAIN[15].fa (.a (A[15]), .b (B[15]), .cin (c[15]),
       .sum (sum[15]), .cout (c[16]));
  full_adder_47 \FA_CHAIN[16].fa (.a (A[16]), .b (B[16]), .cin (c[16]),
       .sum (sum[16]), .cout (c[17]));
  full_adder_46 \FA_CHAIN[17].fa (.a (A[17]), .b (B[17]), .cin (c[17]),
       .sum (sum[17]), .cout (c[18]));
  full_adder_45 \FA_CHAIN[18].fa (.a (A[18]), .b (B[18]), .cin (c[18]),
       .sum (sum[18]), .cout (c[19]));
  full_adder_44 \FA_CHAIN[19].fa (.a (A[19]), .b (B[19]), .cin (c[19]),
       .sum (sum[19]), .cout (c[20]));
  full_adder_43 \FA_CHAIN[20].fa (.a (A[20]), .b (B[20]), .cin (c[20]),
       .sum (sum[20]), .cout (c[21]));
  full_adder_42 \FA_CHAIN[21].fa (.a (A[21]), .b (B[21]), .cin (c[21]),
       .sum (sum[21]), .cout (c[22]));
  full_adder_41 \FA_CHAIN[22].fa (.a (A[22]), .b (B[22]), .cin (c[22]),
       .sum (sum[22]), .cout (c[23]));
  full_adder_40 \FA_CHAIN[23].fa (.a (A[23]), .b (B[23]), .cin (c[23]),
       .sum (sum[23]), .cout (c[24]));
  full_adder_39 \FA_CHAIN[24].fa (.a (A[24]), .b (B[24]), .cin (c[24]),
       .sum (sum[24]), .cout (c[25]));
  full_adder_38 \FA_CHAIN[25].fa (.a (A[25]), .b (B[25]), .cin (c[25]),
       .sum (sum[25]), .cout (c[26]));
  full_adder_37 \FA_CHAIN[26].fa (.a (A[26]), .b (B[26]), .cin (c[26]),
       .sum (sum[26]), .cout (c[27]));
  full_adder_36 \FA_CHAIN[27].fa (.a (A[27]), .b (B[27]), .cin (c[27]),
       .sum (sum[27]), .cout (c[28]));
  full_adder_35 \FA_CHAIN[28].fa (.a (A[28]), .b (B[28]), .cin (c[28]),
       .sum (sum[28]), .cout (c[29]));
  full_adder_34 \FA_CHAIN[29].fa (.a (A[29]), .b (B[29]), .cin (c[29]),
       .sum (sum[29]), .cout (c[30]));
  full_adder_33 \FA_CHAIN[30].fa (.a (A[30]), .b (B[30]), .cin (c[30]),
       .sum (sum[30]), .cout (c[31]));
  full_adder_32 \FA_CHAIN[31].fa (.a (A[31]), .b (B[31]), .cin (c[31]),
       .sum (sum[31]), .cout (cout));
endmodule

