
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr 17 2026 20:18:17 IST (Apr 17 2026 14:48:17 UTC)

// Verification Directory fv/CLA64 

module initialize(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_126(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3, n_8;
  CLKAND2X2 g29__4319(.A (n_3), .B (n_8), .Y (p));
  NAND2X1 g31__5526(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OR2XL g2(.A (y), .B (x), .Y (n_8));
endmodule

module initialize_125(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_4, n_10;
  NAND2X2 g30__3680(.A (n_1), .B (n_2), .Y (n_4));
  CLKINVX1 g32(.A (x), .Y (n_2));
  INVX2 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt35(.A (n_10), .Y (g));
  NAND2X2 g31__36(.A (x), .B (y), .Y (n_10));
  AND2X6 g29__37(.A (n_10), .B (n_4), .Y (p));
endmodule

module initialize_124(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3;
  NAND2X1 g31__5122(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OA21X1 g2(.A0 (y), .A1 (x), .B0 (n_3), .Y (p));
endmodule

module CLA4(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_30;
  initialize ini0(A[0], B[0], G[0], P[0]);
  initialize_126 ini1(A[1], B[1], G[1], P[1]);
  initialize_125 ini2(A[2], B[2], G[2], P[2]);
  initialize_124 ini3(A[3], B[3], G[3], P[3]);
  CLKINVX1 g43(.A (G[3]), .Y (n_14));
  MXI2XL g146__8246(.A (P[2]), .B (n_2), .S0 (n_13), .Y (S[2]));
  AOI21X1 g147__7098(.A0 (P[1]), .A1 (n_10), .B0 (G[1]), .Y (n_13));
  CLKXOR2X1 g148__6131(.A (P[3]), .B (n_12), .Y (S[3]));
  NAND3X1 g149__1881(.A (n_11), .B (n_8), .C (n_30), .Y (n_12));
  MXI2XL g150__5115(.A (n_3), .B (P[1]), .S0 (n_10), .Y (S[1]));
  OR3XL g151__7482(.A (n_3), .B (n_2), .C (n_6), .Y (n_11));
  OAI221X4 g152__4733(.A0 (n_4), .A1 (n_8), .B0 (n_4), .B1 (n_9), .C0
       (n_14), .Y (GG));
  NAND2BX1 g153__6161(.AN (G[0]), .B (n_6), .Y (n_10));
  OA21X1 g154__9315(.A0 (Cin), .A1 (P[0]), .B0 (n_6), .Y (S[0]));
  AOI21X2 g155__9945(.A0 (G[1]), .A1 (P[2]), .B0 (G[2]), .Y (n_9));
  NOR2X2 g156__2883(.A (n_7), .B (n_5), .Y (GP));
  NAND3X4 g157__2346(.A (G[0]), .B (P[1]), .C (P[2]), .Y (n_8));
  NAND2X1 g158__1666(.A (P[2]), .B (P[3]), .Y (n_7));
  NAND2X1 g159__7410(.A (P[1]), .B (P[0]), .Y (n_5));
  NAND2XL g160__6417(.A (Cin), .B (P[0]), .Y (n_6));
  CLKINVX2 g161(.A (P[3]), .Y (n_4));
  CLKINVX1 g162(.A (P[1]), .Y (n_3));
  CLKINVX1 g163(.A (P[2]), .Y (n_2));
  CLKBUFX2 fopt181(.A (n_9), .Y (n_30));
endmodule

module initialize_123(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_122(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX2 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_121(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3, n_14;
  CLKAND2X3 g29__5526(.A (n_3), .B (n_14), .Y (p));
  NAND2X1 g31__3680(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OR2XL g2(.A (y), .B (x), .Y (n_14));
endmodule

module initialize_120(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_3, n_4, n_14;
  CLKAND2X6 g29__1617(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__2802(.A (n_1), .B (n_14), .Y (n_4));
  NAND2X2 g31__1705(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g33(.A (y), .Y (n_1));
  INVXL fopt(.A (n_3), .Y (g));
  INVX1 fopt37(.A (x), .Y (n_14));
endmodule

module CLA4_30(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_14, n_15, n_17, n_18, n_45, n_50, n_52;
  initialize_123 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_122 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_121 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_120 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  NAND3X2 g54__5122(.A (n_18), .B (n_17), .C (n_52), .Y (GG));
  AOI21X2 g55__8246(.A0 (G[2]), .A1 (P[3]), .B0 (G[3]), .Y (n_18));
  NAND3X1 g56__7098(.A (G[1]), .B (P[3]), .C (P[2]), .Y (n_17));
  NOR2X4 g57__6131(.A (n_14), .B (n_15), .Y (GP));
  NAND2X2 g59__5115(.A (P[1]), .B (P[0]), .Y (n_15));
  NAND2X2 g60__7482(.A (P[2]), .B (P[3]), .Y (n_14));
  OAI21X1 g114__9315(.A0 (P[2]), .A1 (n_7), .B0 (n_8), .Y (S[2]));
  NAND2XL g115__9945(.A (P[2]), .B (n_7), .Y (n_8));
  AOI21X1 g116__2883(.A0 (n_45), .A1 (n_3), .B0 (G[1]), .Y (n_7));
  OAI21X1 g117__2346(.A0 (P[3]), .A1 (n_5), .B0 (n_6), .Y (S[3]));
  NAND2XL g118__1666(.A (P[3]), .B (n_5), .Y (n_6));
  AOI211X1 g119__7410(.A0 (P[2]), .A1 (G[1]), .B0 (n_4), .C0 (G[2]), .Y
       (n_5));
  MXI2XL g120__6417(.A (n_2), .B (n_3), .S0 (n_45), .Y (S[1]));
  NAND2XL g121__5477(.A (n_0), .B (n_1), .Y (n_4));
  CLKINVX1 g122(.A (n_2), .Y (n_3));
  AOI21X1 g123__2398(.A0 (Cin), .A1 (P[0]), .B0 (G[0]), .Y (n_2));
  NAND4XL g124__5107(.A (P[2]), .B (n_45), .C (Cin), .D (P[0]), .Y
       (n_1));
  NAND3XL g125__6260(.A (G[0]), .B (P[2]), .C (n_45), .Y (n_0));
  CLKXOR2X1 g126__4319(.A (P[0]), .B (Cin), .Y (S[0]));
  CLKINVX1 fopt133(.A (n_50), .Y (n_45));
  INVXL fopt134(.A (P[1]), .Y (n_50));
  NAND4X2 g2(.A (G[0]), .B (P[1]), .C (P[2]), .D (P[3]), .Y (n_52));
endmodule

module initialize_119(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX2 g35(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_118(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_3, n_4, n_8;
  CLKAND2X6 g29__3680(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__1617(.A (n_1), .B (n_8), .Y (n_4));
  NAND2X2 g31__2802(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g33(.A (y), .Y (n_1));
  INVXL fopt(.A (n_3), .Y (g));
  INVX1 fopt34(.A (x), .Y (n_8));
endmodule

module initialize_117(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__1705(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__5122(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__8246(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  INVX2 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_116(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  CLKAND2X6 g29__7098(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__6131(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__1881(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  CLKINVX1 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module CLA4_29(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_29, n_32, n_36;
  initialize_119 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_118 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_117 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_116 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  CLKINVX1 g44(.A (G[3]), .Y (n_12));
  OAI211X1 g66__5115(.A0 (n_36), .A1 (n_11), .B0 (n_10), .C0 (n_12), .Y
       (GG));
  AOI21X1 g67__7482(.A0 (P[2]), .A1 (G[1]), .B0 (G[2]), .Y (n_11));
  NAND4X1 g68__4733(.A (G[0]), .B (P[3]), .C (P[1]), .D (P[2]), .Y
       (n_10));
  NOR2X4 g69__6161(.A (n_8), .B (n_9), .Y (GP));
  NAND2X4 g70__9315(.A (P[3]), .B (P[2]), .Y (n_9));
  NAND2X4 g71__9945(.A (P[0]), .B (P[1]), .Y (n_8));
  NAND2XL g72__2883(.A (n_29), .B (G[1]), .Y (n_13));
  OAI21X1 g118__2346(.A0 (n_29), .A1 (n_5), .B0 (n_6), .Y (S[2]));
  NAND2XL g119__1666(.A (n_29), .B (n_5), .Y (n_6));
  AOI21X1 g121__6417(.A0 (P[1]), .A1 (n_2), .B0 (G[1]), .Y (n_5));
  NAND3X1 g122__5477(.A (n_3), .B (n_13), .C (n_1), .Y (n_4));
  AOI31X1 g123__2398(.A0 (P[1]), .A1 (n_29), .A2 (n_0), .B0 (G[2]), .Y
       (n_3));
  CLKXOR2X1 g124__5107(.A (P[1]), .B (n_2), .Y (S[1]));
  OR2X1 g125__6260(.A (G[0]), .B (n_0), .Y (n_2));
  AOI2BB1X1 g126__4319(.A0N (Cin), .A1N (P[0]), .B0 (n_0), .Y (S[0]));
  NAND3X1 g127__8428(.A (G[0]), .B (n_29), .C (P[1]), .Y (n_1));
  AND2X1 g128__5526(.A (Cin), .B (P[0]), .Y (n_0));
  INVX1 fopt2(.A (n_32), .Y (n_29));
  INVX1 fopt3(.A (P[2]), .Y (n_32));
  CLKINVX1 fopt130(.A (P[3]), .Y (n_36));
  XNOR2X1 g2(.A (n_36), .B (n_4), .Y (S[3]));
endmodule

module initialize_115(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_114(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  CLKAND2X6 g29__2802(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__1705(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__5122(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  CLKINVX1 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_113(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__8246(.A (n_3), .B (n_4), .Y (p));
  NAND2X1 g30__7098(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X1 g31__6131(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  CLKINVX1 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_112(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3;
  NAND2X1 g31__7482(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OA21X4 g34(.A0 (y), .A1 (x), .B0 (n_3), .Y (p));
endmodule

module CLA4_28(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_30;
  initialize_115 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_114 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_113 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_112 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  CLKINVX1 g44(.A (G[3]), .Y (n_13));
  OAI211X1 g66__4733(.A0 (n_8), .A1 (n_12), .B0 (n_11), .C0 (n_13), .Y
       (GG));
  AOI21X1 g67__6161(.A0 (P[2]), .A1 (G[1]), .B0 (G[2]), .Y (n_12));
  NAND4XL g68__9315(.A (P[2]), .B (P[3]), .C (P[1]), .D (G[0]), .Y
       (n_11));
  NOR2X4 g69__9945(.A (n_9), .B (n_10), .Y (GP));
  NAND2X4 g70__2883(.A (P[3]), .B (P[2]), .Y (n_10));
  NAND2X2 g71__2346(.A (P[0]), .B (P[1]), .Y (n_9));
  NAND2XL g72__1666(.A (P[2]), .B (G[1]), .Y (n_14));
  INVX1 g73(.A (P[3]), .Y (n_8));
  CLKXOR2X1 g120__5477(.A (P[3]), .B (n_5), .Y (S[3]));
  NAND3X1 g122__5107(.A (n_4), .B (n_14), .C (n_1), .Y (n_5));
  AOI31X1 g123__6260(.A0 (P[1]), .A1 (P[2]), .A2 (n_2), .B0 (G[2]), .Y
       (n_4));
  CLKXOR2X1 g124__4319(.A (P[1]), .B (n_3), .Y (S[1]));
  NAND2BX1 g125__8428(.AN (G[0]), .B (n_0), .Y (n_3));
  INVX1 g126(.A (n_0), .Y (n_2));
  OA21X1 g127__5526(.A0 (Cin), .A1 (P[0]), .B0 (n_0), .Y (S[0]));
  NAND3X1 g128__6783(.A (G[0]), .B (P[2]), .C (P[1]), .Y (n_1));
  NAND2XL g129__3680(.A (Cin), .B (P[0]), .Y (n_0));
  XNOR2X1 g2(.A (n_30), .B (P[2]), .Y (S[2]));
  AOI21XL g3(.A0 (P[1]), .A1 (n_3), .B0 (G[1]), .Y (n_30));
endmodule

module CLA16(A, B, Cin, S, GG, GP);
  input [15:0] A, B;
  input Cin;
  output [15:0] S;
  output GG, GP;
  wire [15:0] A, B;
  wire Cin;
  wire [15:0] S;
  wire GG, GP;
  wire [3:0] GG4;
  wire [3:0] GP4;
  wire c4, c8, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_63;
  CLA4 grp0(A[3:0], B[3:0], Cin, S[3:0], GG4[0], GP4[0]);
  CLA4_30 grp1(A[7:4], B[7:4], c4, S[7:4], GG4[1], GP4[1]);
  CLA4_29 grp2(A[11:8], B[11:8], c8, S[11:8], GG4[2], GP4[2]);
  CLA4_28 grp3(A[15:12], B[15:12], n_63, S[15:12], GG4[3], GP4[3]);
  CLKINVX1 g18(.A (GG4[2]), .Y (n_11));
  AO21X1 g69__2802(.A0 (GP4[1]), .A1 (c4), .B0 (GG4[1]), .Y (c8));
  NAND2X4 g70__1705(.A (n_10), .B (n_9), .Y (GG));
  AOI31X2 g71__5122(.A0 (GG4[0]), .A1 (GP4[1]), .A2 (n_2), .B0
       (GG4[3]), .Y (n_10));
  NAND2X2 g72__8246(.A (GP4[3]), .B (n_7), .Y (n_9));
  NAND3X1 g73__7098(.A (GP4[1]), .B (GP4[2]), .C (n_3), .Y (n_8));
  OR2X1 g75__6131(.A (GG4[0]), .B (n_3), .Y (c4));
  NAND2X2 g76__1881(.A (n_11), .B (n_1), .Y (n_7));
  NAND3X1 g77__5115(.A (GG4[0]), .B (GP4[2]), .C (GP4[1]), .Y (n_6));
  NOR2X2 g78__7482(.A (n_5), .B (n_4), .Y (GP));
  NAND2X1 g79__4733(.A (GP4[3]), .B (GP4[2]), .Y (n_5));
  NAND2X2 g80__6161(.A (GP4[1]), .B (GP4[0]), .Y (n_4));
  CLKAND2X2 g81__9315(.A (GP4[2]), .B (GP4[3]), .Y (n_2));
  NAND2X1 g82__9945(.A (GP4[2]), .B (GG4[1]), .Y (n_1));
  AND2X1 g83__2883(.A (Cin), .B (GP4[0]), .Y (n_3));
  NAND3BX1 g2(.AN (n_7), .B (n_6), .C (n_8), .Y (n_63));
endmodule

module initialize_111(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_110(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3, n_10;
  CLKAND2X2 g29__6417(.A (n_3), .B (n_10), .Y (p));
  NAND2XL g31__2398(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OR2XL g2(.A (y), .B (x), .Y (n_10));
endmodule

module initialize_109(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  CLKAND2X2 g29__5107(.A (n_3), .B (n_4), .Y (p));
  NAND2XL g30__6260(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X1 g31__4319(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  CLKINVX1 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_108(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3, n_10;
  CLKAND2X3 g29__8428(.A (n_3), .B (n_10), .Y (p));
  NAND2X1 g31__6783(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OR2XL g2(.A (y), .B (x), .Y (n_10));
endmodule

module CLA4_27(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_11, n_12, n_14, n_15, n_51;
  initialize_111 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_110 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_109 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_108 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  NAND3X2 g54__3680(.A (n_15), .B (n_14), .C (n_51), .Y (GG));
  AOI21X2 g55__1617(.A0 (G[2]), .A1 (P[3]), .B0 (G[3]), .Y (n_15));
  NAND3X1 g56__2802(.A (G[1]), .B (P[2]), .C (P[3]), .Y (n_14));
  NOR2X2 g57__1705(.A (n_11), .B (n_12), .Y (GP));
  NAND2X1 g59__8246(.A (P[1]), .B (P[0]), .Y (n_12));
  NAND2X1 g60__7098(.A (P[2]), .B (P[3]), .Y (n_11));
  OAI21X1 g114__5115(.A0 (P[2]), .A1 (n_7), .B0 (n_8), .Y (S[2]));
  NAND2XL g115__7482(.A (P[2]), .B (n_7), .Y (n_8));
  AOI21X1 g116__4733(.A0 (P[1]), .A1 (n_3), .B0 (G[1]), .Y (n_7));
  OAI21XL g117__6161(.A0 (P[3]), .A1 (n_5), .B0 (n_6), .Y (S[3]));
  NAND2XL g118__9315(.A (P[3]), .B (n_5), .Y (n_6));
  AOI211X1 g119__9945(.A0 (P[2]), .A1 (G[1]), .B0 (n_4), .C0 (G[2]), .Y
       (n_5));
  MXI2XL g120__2883(.A (n_2), .B (n_3), .S0 (P[1]), .Y (S[1]));
  NAND2XL g121__2346(.A (n_0), .B (n_1), .Y (n_4));
  CLKINVX1 g122(.A (n_2), .Y (n_3));
  AOI21X1 g123__1666(.A0 (Cin), .A1 (P[0]), .B0 (G[0]), .Y (n_2));
  NAND4XL g124__7410(.A (P[2]), .B (P[1]), .C (Cin), .D (P[0]), .Y
       (n_1));
  NAND3XL g125__6417(.A (G[0]), .B (P[2]), .C (P[1]), .Y (n_0));
  CLKXOR2X1 g126__5477(.A (Cin), .B (P[0]), .Y (S[0]));
  NAND4X2 g2(.A (G[0]), .B (P[1]), .C (P[2]), .D (P[3]), .Y (n_51));
endmodule

module initialize_107(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3, n_12;
  AND2X1 g29__2398(.A (n_3), .B (n_12), .Y (p));
  NAND2XL g31__6260(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OR2XL g2(.A (y), .B (x), .Y (n_12));
endmodule

module initialize_106(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__4319(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__8428(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__5526(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  INVX2 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_105(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__6783(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__3680(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__1617(.A (x), .B (y), .Y (n_3));
  INVX2 g32(.A (x), .Y (n_2));
  INVX2 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_104(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__2802(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__1705(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__5122(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  INVX2 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module CLA4_26(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17;
  initialize_107 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_106 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_105 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_104 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  NAND2X1 g53__8246(.A (n_17), .B (n_16), .Y (GG));
  AOI31X1 g54__7098(.A0 (G[1]), .A1 (P[2]), .A2 (P[3]), .B0 (G[3]), .Y
       (n_17));
  NOR2X2 g55__6131(.A (n_12), .B (n_15), .Y (n_16));
  NOR2X2 g56__1881(.A (n_13), .B (n_14), .Y (GP));
  NOR2X1 g57__5115(.A (n_11), .B (n_10), .Y (n_15));
  NAND2X1 g58__7482(.A (P[1]), .B (P[0]), .Y (n_14));
  NAND2X2 g59__4733(.A (P[2]), .B (P[3]), .Y (n_13));
  NOR2BX1 g60__6161(.AN (G[2]), .B (n_9), .Y (n_12));
  NAND2X1 g61__9315(.A (P[3]), .B (P[2]), .Y (n_11));
  NAND2X1 g62__9945(.A (P[1]), .B (G[0]), .Y (n_10));
  INVX1 g63(.A (P[3]), .Y (n_9));
  OAI21X1 g114__2883(.A0 (P[2]), .A1 (n_7), .B0 (n_8), .Y (S[2]));
  NAND2XL g115__2346(.A (n_7), .B (P[2]), .Y (n_8));
  AOI21X1 g116__1666(.A0 (P[1]), .A1 (n_4), .B0 (G[1]), .Y (n_7));
  OAI21X1 g117__7410(.A0 (P[3]), .A1 (n_5), .B0 (n_6), .Y (S[3]));
  NAND2XL g118__6417(.A (n_5), .B (P[3]), .Y (n_6));
  AND3X1 g119__5477(.A (n_1), .B (n_0), .C (n_2), .Y (n_5));
  MXI2XL g120__2398(.A (n_3), .B (n_4), .S0 (P[1]), .Y (S[1]));
  CLKINVX1 g121(.A (n_3), .Y (n_4));
  AOI21X1 g122__5107(.A0 (Cin), .A1 (P[0]), .B0 (G[0]), .Y (n_3));
  NAND4XL g123__6260(.A (P[2]), .B (P[1]), .C (Cin), .D (P[0]), .Y
       (n_2));
  AOI21X1 g124__4319(.A0 (P[2]), .A1 (G[1]), .B0 (G[2]), .Y (n_1));
  NAND3XL g125__8428(.A (G[0]), .B (P[2]), .C (P[1]), .Y (n_0));
  CLKXOR2X1 g126__5526(.A (P[0]), .B (Cin), .Y (S[0]));
endmodule

module initialize_103(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3;
  NAND2X1 g31__1617(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OA21X1 g34(.A0 (y), .A1 (x), .B0 (n_3), .Y (p));
endmodule

module initialize_102(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3;
  NAND2X1 g31__5122(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OA21X1 g2(.A0 (y), .A1 (x), .B0 (n_3), .Y (p));
endmodule

module initialize_101(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__8246(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__7098(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__6131(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  INVX2 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_100(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__1881(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__5115(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__7482(.A (x), .B (y), .Y (n_3));
  INVX2 g32(.A (x), .Y (n_2));
  INVX2 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module CLA4_25(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_39;
  wire n_44, n_49, n_50, n_51;
  initialize_103 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_102 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_101 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_100 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  NOR2X4 g57__9945(.A (n_17), .B (n_16), .Y (GP));
  NAND2X2 g59__2346(.A (P[1]), .B (P[0]), .Y (n_17));
  NAND2X2 g60__1666(.A (P[2]), .B (P[3]), .Y (n_16));
  OAI21X1 g114__7410(.A0 (n_39), .A1 (n_14), .B0 (n_15), .Y (S[2]));
  NAND2X1 g115__6417(.A (n_39), .B (n_14), .Y (n_15));
  AOI21X1 g116__5477(.A0 (n_0), .A1 (n_9), .B0 (G[1]), .Y (n_14));
  OAI21X1 g117__2398(.A0 (P[3]), .A1 (n_12), .B0 (n_13), .Y (S[3]));
  NAND2XL g118__5107(.A (n_12), .B (P[3]), .Y (n_13));
  NOR2BX1 g119__6260(.AN (n_8), .B (n_11), .Y (n_12));
  OAI21X1 g121__8428(.A0 (n_6), .A1 (n_5), .B0 (n_7), .Y (n_11));
  NAND2BX2 g123__5526(.AN (G[0]), .B (n_4), .Y (n_9));
  AOI21X1 g124__6783(.A0 (n_39), .A1 (G[1]), .B0 (G[2]), .Y (n_8));
  NAND3X1 g125__3680(.A (G[0]), .B (P[2]), .C (n_0), .Y (n_7));
  CLKXOR2X1 g126__1617(.A (P[0]), .B (Cin), .Y (S[0]));
  NAND2XL g127__2802(.A (P[2]), .B (n_0), .Y (n_6));
  NAND2XL g128__1705(.A (Cin), .B (P[0]), .Y (n_5));
  NAND2X1 g129__5122(.A (Cin), .B (P[0]), .Y (n_4));
  CLKINVX1 drc_bufs130(.A (n_1), .Y (n_0));
  INVX1 drc_bufs131(.A (P[1]), .Y (n_1));
  INVX1 fopt3(.A (n_44), .Y (n_39));
  CLKINVX1 fopt5(.A (P[2]), .Y (n_44));
  NAND3X2 g54__137(.A (n_49), .B (n_50), .C (n_51), .Y (GG));
  NAND4X1 g58__138(.A (P[3]), .B (P[2]), .C (P[1]), .D (G[0]), .Y
       (n_49));
  NAND3X1 g56__139(.A (G[1]), .B (P[3]), .C (P[2]), .Y (n_50));
  AOI21X2 g55__140(.A0 (P[3]), .A1 (G[2]), .B0 (G[3]), .Y (n_51));
  CLKXOR2X1 g141(.A (n_9), .B (n_0), .Y (S[1]));
endmodule

module initialize_99(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_98(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3;
  NAND2X1 g31__7482(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OA21X1 g2(.A0 (y), .A1 (x), .B0 (n_3), .Y (p));
endmodule

module initialize_97(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__4733(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__6161(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X1 g31__9315(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  CLKINVX1 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_96(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__9945(.A (n_3), .B (n_4), .Y (p));
  NAND2X1 g30__2883(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X1 g31__2346(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  CLKINVX1 g33(.A (y), .Y (n_1));
  INVXL fopt1(.A (n_3), .Y (g));
endmodule

module CLA4_24(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_42, n_45;
  initialize_99 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_98 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_97 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_96 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  NAND3X2 g54__1666(.A (n_18), .B (n_17), .C (n_16), .Y (GG));
  AOI21X2 g55__7410(.A0 (P[3]), .A1 (G[2]), .B0 (G[3]), .Y (n_18));
  NAND3XL g56__6417(.A (G[1]), .B (P[3]), .C (P[2]), .Y (n_17));
  NOR2X4 g57__5477(.A (n_15), .B (n_14), .Y (GP));
  NAND4XL g58__2398(.A (P[3]), .B (P[2]), .C (P[1]), .D (G[0]), .Y
       (n_16));
  NAND2X2 g59__5107(.A (P[1]), .B (P[0]), .Y (n_15));
  NAND2X2 g60__6260(.A (P[2]), .B (P[3]), .Y (n_14));
  OAI21X1 g114__4319(.A0 (n_42), .A1 (n_12), .B0 (n_13), .Y (S[2]));
  NAND2XL g115__8428(.A (n_42), .B (n_12), .Y (n_13));
  AOI21X2 g116__5526(.A0 (n_1), .A1 (n_7), .B0 (G[1]), .Y (n_12));
  OAI21X1 g117__6783(.A0 (P[3]), .A1 (n_10), .B0 (n_11), .Y (S[3]));
  NAND2X1 g118__3680(.A (n_10), .B (P[3]), .Y (n_11));
  NOR2BX1 g119__1617(.AN (n_6), .B (n_9), .Y (n_10));
  OAI21X1 g121__1705(.A0 (n_4), .A1 (n_3), .B0 (n_5), .Y (n_9));
  NAND2BX1 g123__5122(.AN (G[0]), .B (n_2), .Y (n_7));
  AOI21X1 g124__8246(.A0 (n_42), .A1 (G[1]), .B0 (G[2]), .Y (n_6));
  NAND3X1 g125__7098(.A (G[0]), .B (P[2]), .C (n_1), .Y (n_5));
  CLKXOR2X1 g126__6131(.A (P[0]), .B (Cin), .Y (S[0]));
  NAND2XL g127__1881(.A (P[2]), .B (n_1), .Y (n_4));
  NAND2XL g128__5115(.A (Cin), .B (P[0]), .Y (n_3));
  NAND2X1 g129__7482(.A (Cin), .B (P[0]), .Y (n_2));
  CLKINVX1 drc_bufs130(.A (n_0), .Y (n_1));
  INVX1 drc_bufs131(.A (P[1]), .Y (n_0));
  CLKINVX1 fopt135(.A (n_45), .Y (n_42));
  INVX1 fopt3(.A (P[2]), .Y (n_45));
  CLKXOR2X1 g2(.A (n_7), .B (n_1), .Y (S[1]));
endmodule

module CLA16_6(A, B, Cin, S, GG, GP);
  input [15:0] A, B;
  input Cin;
  output [15:0] S;
  output GG, GP;
  wire [15:0] A, B;
  wire Cin;
  wire [15:0] S;
  wire GG, GP;
  wire [3:0] GG4;
  wire [3:0] GP4;
  wire c4, c8, c12, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_63, n_65, n_67;
  wire n_68, n_71, n_72, n_75, n_76;
  CLA4_27 grp0(.A (A[3:0]), .B (B[3:0]), .Cin (Cin), .S (S[3:0]), .GG
       (GG4[0]), .GP (GP4[0]));
  CLA4_26 grp1(.A (A[7:4]), .B (B[7:4]), .Cin (c4), .S (S[7:4]), .GG
       (GG4[1]), .GP (GP4[1]));
  CLA4_25 grp2(.A (A[11:8]), .B (B[11:8]), .Cin (c8), .S (S[11:8]), .GG
       (GG4[2]), .GP (GP4[2]));
  CLA4_24 grp3(.A (A[15:12]), .B (B[15:12]), .Cin (c12), .S (S[15:12]),
       .GG (GG4[3]), .GP (GP4[3]));
  NAND3X2 g36__4733(.A (n_11), .B (n_10), .C (n_9), .Y (GG));
  AOI21X2 g37__6161(.A0 (GP4[3]), .A1 (GG4[2]), .B0 (GG4[3]), .Y
       (n_11));
  NAND2BX1 g38__9315(.AN (n_7), .B (GG4[1]), .Y (n_10));
  NOR2X2 g39__9945(.A (n_7), .B (n_8), .Y (GP));
  NAND4X1 g40__2883(.A (GP4[3]), .B (GP4[2]), .C (GP4[1]), .D (GG4[0]),
       .Y (n_9));
  NAND2X2 g41__2346(.A (GP4[1]), .B (GP4[0]), .Y (n_8));
  NAND2X2 g44__1666(.A (GP4[3]), .B (GP4[2]), .Y (n_7));
  OAI21X2 g48__7410(.A0 (n_67), .A1 (n_5), .B0 (n_71), .Y (c8));
  NAND3X2 g49__6417(.A (n_6), .B (n_3), .C (n_4), .Y (c12));
  AOI31X1 g50__5477(.A0 (n_63), .A1 (GP4[2]), .A2 (n_68), .B0 (GG4[2]),
       .Y (n_6));
  CLKINVX2 g51(.A (n_5), .Y (c4));
  AOI21X2 g52__2398(.A0 (n_75), .A1 (Cin), .B0 (n_63), .Y (n_5));
  NAND3X1 g53__5107(.A (n_2), .B (Cin), .C (GP4[0]), .Y (n_4));
  NAND2XL g54__6260(.A (GP4[2]), .B (n_72), .Y (n_3));
  NOR2BX1 g55__4319(.AN (GP4[2]), .B (n_67), .Y (n_2));
  INVX1 fopt(.A (n_65), .Y (n_63));
  INVXL fopt2(.A (GG4[0]), .Y (n_65));
  CLKINVX1 fopt59(.A (n_67), .Y (n_68));
  INVX1 fopt60(.A (GP4[1]), .Y (n_67));
  INVXL fopt61(.A (n_72), .Y (n_71));
  CLKBUFX2 fopt62(.A (GG4[1]), .Y (n_72));
  INVX1 fopt64(.A (n_76), .Y (n_75));
  CLKINVX1 fopt65(.A (GP4[0]), .Y (n_76));
endmodule

module initialize_95(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_94(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  CLKAND2X3 g29__3680(.A (n_3), .B (n_4), .Y (p));
  NAND2X1 g30__1617(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X1 g31__2802(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  CLKINVX1 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_93(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__1705(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__5122(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__8246(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  INVX2 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_92(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3;
  NAND2X1 g31__1881(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OA21X4 g2(.A0 (y), .A1 (x), .B0 (n_3), .Y (p));
endmodule

module CLA4_23(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_3, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_30;
  initialize_95 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_94 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_93 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_92 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  CLKINVX1 g44(.A (G[3]), .Y (n_13));
  OAI211X2 g66__5115(.A0 (n_8), .A1 (n_12), .B0 (n_11), .C0 (n_13), .Y
       (GG));
  AOI21X2 g67__7482(.A0 (G[1]), .A1 (P[2]), .B0 (G[2]), .Y (n_12));
  NAND4X2 g68__4733(.A (G[0]), .B (P[3]), .C (P[1]), .D (P[2]), .Y
       (n_11));
  NOR2X2 g69__6161(.A (n_10), .B (n_9), .Y (GP));
  NAND2X2 g70__9315(.A (P[3]), .B (P[2]), .Y (n_10));
  NAND2XL g71__9945(.A (P[1]), .B (P[0]), .Y (n_9));
  NAND2XL g72__2883(.A (P[2]), .B (G[1]), .Y (n_14));
  CLKINVX1 g73(.A (P[3]), .Y (n_8));
  OAI21X1 g118__2346(.A0 (P[2]), .A1 (n_6), .B0 (n_7), .Y (S[2]));
  NAND2XL g119__1666(.A (P[2]), .B (n_6), .Y (n_7));
  CLKXOR2X1 g120__7410(.A (P[3]), .B (n_5), .Y (S[3]));
  AOI21X1 g121__6417(.A0 (P[1]), .A1 (n_3), .B0 (G[1]), .Y (n_6));
  NAND4BX1 g122__5477(.AN (G[2]), .B (n_14), .C (n_1), .D (n_30), .Y
       (n_5));
  CLKXOR2X1 g123__2398(.A (P[1]), .B (n_3), .Y (S[1]));
  NAND2BX1 g125__6260(.AN (G[0]), .B (n_0), .Y (n_3));
  OA21X1 g127__4319(.A0 (Cin), .A1 (P[0]), .B0 (n_0), .Y (S[0]));
  NAND3XL g128__8428(.A (G[0]), .B (P[2]), .C (P[1]), .Y (n_1));
  NAND2X1 g129__5526(.A (Cin), .B (P[0]), .Y (n_0));
  NAND3BX1 g2(.AN (n_0), .B (P[1]), .C (P[2]), .Y (n_30));
endmodule

module initialize_91(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_90(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__2802(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__1705(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X1 g31__5122(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  CLKINVX1 g33(.A (y), .Y (n_1));
  INVXL fopt(.A (n_3), .Y (g));
endmodule

module initialize_89(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3;
  NAND2X1 g31__6131(.A (x), .B (y), .Y (n_3));
  INVXL fopt(.A (n_3), .Y (g));
  OA21X1 g2(.A0 (y), .A1 (x), .B0 (n_3), .Y (p));
endmodule

module initialize_88(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g34(.A (x), .B (y), .CO (g), .S (p));
endmodule

module CLA4_22(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_4, n_6, n_8, n_9, n_11;
  wire n_12, n_14, n_15, n_16, n_17, n_41, n_45, n_46;
  initialize_91 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_90 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_89 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_88 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  CLKINVX1 g46(.A (G[3]), .Y (n_17));
  OAI21X1 g116__4733(.A0 (n_41), .A1 (n_15), .B0 (n_16), .Y (S[2]));
  NAND2XL g117__6161(.A (n_41), .B (n_15), .Y (n_16));
  AOI21X2 g118__9315(.A0 (P[1]), .A1 (n_12), .B0 (G[1]), .Y (n_15));
  MXI2X1 g119__9945(.A (n_1), .B (P[3]), .S0 (n_14), .Y (S[3]));
  NAND3BX1 g121__2346(.AN (G[2]), .B (n_45), .C (n_11), .Y (n_14));
  NAND2BX2 g123__1666(.AN (G[0]), .B (n_8), .Y (n_12));
  NAND3BX1 g124__7410(.AN (n_9), .B (Cin), .C (P[0]), .Y (n_11));
  CLKXOR2X1 g125__6417(.A (P[0]), .B (Cin), .Y (S[0]));
  NAND2XL g127__2398(.A (n_41), .B (P[1]), .Y (n_9));
  NAND2X2 g128__5107(.A (P[0]), .B (Cin), .Y (n_8));
  OAI21X2 g74__6260(.A0 (n_1), .A1 (n_6), .B0 (n_17), .Y (GG));
  NOR3X2 g75__4319(.A (G[2]), .B (n_0), .C (n_46), .Y (n_6));
  NOR2X2 g78__5526(.A (n_4), .B (n_2), .Y (GP));
  NAND2X1 g80__6783(.A (P[2]), .B (P[3]), .Y (n_4));
  NAND2X1 g83__1617(.A (P[1]), .B (P[0]), .Y (n_2));
  CLKINVX1 g84(.A (P[3]), .Y (n_1));
  AND2X1 g2__2802(.A (G[1]), .B (P[2]), .Y (n_0));
  CLKXOR2X1 g2(.A (P[1]), .B (n_12), .Y (S[1]));
  CLKBUFX2 fopt1(.A (P[2]), .Y (n_41));
  NOR2XL g133(.A (n_0), .B (n_46), .Y (n_45));
  AND3X1 g134(.A (G[0]), .B (P[2]), .C (P[1]), .Y (n_46));
endmodule

module initialize_87(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3, n_8;
  CLKAND2X2 g29__1705(.A (n_3), .B (n_8), .Y (p));
  NAND2XL g31__8246(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OR2XL g2(.A (y), .B (x), .Y (n_8));
endmodule

module initialize_86(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  CLKAND2X3 g29__7098(.A (n_3), .B (n_4), .Y (p));
  NAND2X1 g30__6131(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X1 g31__1881(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  CLKINVX1 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_85(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__5115(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__7482(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__4733(.A (x), .B (y), .Y (n_3));
  INVX2 g32(.A (x), .Y (n_2));
  INVX2 g33(.A (y), .Y (n_1));
  INVXL fopt1(.A (n_3), .Y (g));
endmodule

module initialize_84(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX2 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module CLA4_21(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_9, n_12;
  wire n_19, n_20, n_39, n_45, n_47, n_49, n_51, n_55;
  wire n_59, n_63, n_66, n_67, n_68, n_69;
  initialize_87 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_86 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_85 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_84 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  CLKINVX1 g46(.A (G[3]), .Y (n_20));
  OAI21X1 g116__2883(.A0 (n_45), .A1 (n_59), .B0 (n_19), .Y (S[2]));
  NAND2X1 g117__2346(.A (n_45), .B (n_59), .Y (n_19));
  CLKXOR2X1 g126__4319(.A (P[0]), .B (n_9), .Y (S[0]));
  AND2XL g128__5526(.A (n_45), .B (P[1]), .Y (n_12));
  CLKBUFX2 fopt(.A (Cin), .Y (n_9));
  OAI21X2 g74__3680(.A0 (n_1), .A1 (n_67), .B0 (n_20), .Y (GG));
  NOR2BX2 g77__2802(.AN (G[0]), .B (n_3), .Y (n_5));
  NOR2X4 g78__1705(.A (n_4), .B (n_2), .Y (GP));
  NAND2X4 g80__5122(.A (P[2]), .B (P[3]), .Y (n_4));
  NAND2X1 g82__8246(.A (P[2]), .B (P[1]), .Y (n_3));
  NAND2X2 g83__7098(.A (P[1]), .B (P[0]), .Y (n_2));
  CLKINVX1 g84(.A (P[3]), .Y (n_1));
  CLKAND2X3 g2__6131(.A (G[1]), .B (P[2]), .Y (n_0));
  CLKINVX1 fopt2(.A (G[2]), .Y (n_39));
  INVX1 fopt136(.A (n_47), .Y (n_45));
  INVXL fopt138(.A (P[2]), .Y (n_47));
  INVX1 fopt140(.A (n_51), .Y (n_49));
  INVX1 fopt141(.A (P[1]), .Y (n_51));
  NAND2X2 g129__143(.A (P[0]), .B (Cin), .Y (n_55));
  AOI21X2 g118__145(.A0 (n_49), .A1 (n_69), .B0 (G[1]), .Y (n_59));
  MXI2X1 g119__147(.A (n_1), .B (P[3]), .S0 (n_66), .Y (S[3]));
  NAND3X1 g125__152(.A (Cin), .B (n_12), .C (P[0]), .Y (n_63));
  NAND3X1 g154(.A (n_39), .B (n_68), .C (n_63), .Y (n_66));
  NOR3BX4 g155(.AN (n_39), .B (n_0), .C (n_5), .Y (n_67));
  NOR2XL g156(.A (n_0), .B (n_5), .Y (n_68));
  NAND2BX2 g4(.AN (G[0]), .B (n_55), .Y (n_69));
  CLKXOR2X1 g2(.A (n_49), .B (n_69), .Y (S[1]));
endmodule

module initialize_83(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3;
  NAND2XL g31__7482(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OA21X1 g34(.A0 (y), .A1 (x), .B0 (n_3), .Y (p));
endmodule

module initialize_82(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__4733(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__6161(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__9315(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  CLKINVX1 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_81(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_1, n_2, n_3, n_4;
  AND2X6 g29__9945(.A (n_3), .B (n_4), .Y (p));
  NAND2X2 g30__2883(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X2 g31__2346(.A (x), .B (y), .Y (n_3));
  CLKINVX1 g32(.A (x), .Y (n_2));
  INVX2 g33(.A (y), .Y (n_1));
  CLKINVX1 fopt(.A (n_3), .Y (g));
endmodule

module initialize_80(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module CLA4_20(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_6, n_8, n_9, n_11, n_12;
  wire n_14, n_15, n_16, n_17, n_34, n_36, n_37, n_43;
  wire n_45, n_46;
  initialize_83 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_82 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_81 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_80 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  CLKINVX1 g46(.A (G[3]), .Y (n_17));
  OAI21X1 g116__5477(.A0 (P[2]), .A1 (n_15), .B0 (n_16), .Y (S[2]));
  NAND2XL g117__2398(.A (P[2]), .B (n_15), .Y (n_16));
  AOI21X2 g118__5107(.A0 (P[1]), .A1 (n_12), .B0 (G[1]), .Y (n_15));
  MXI2X1 g119__6260(.A (n_1), .B (P[3]), .S0 (n_14), .Y (S[3]));
  MXI2X1 g120__4319(.A (n_37), .B (n_36), .S0 (P[1]), .Y (S[1]));
  NAND3BX1 g121__8428(.AN (G[2]), .B (n_45), .C (n_11), .Y (n_14));
  NAND2BX2 g123__5526(.AN (G[0]), .B (n_8), .Y (n_12));
  NAND3BXL g124__6783(.AN (n_9), .B (Cin), .C (P[0]), .Y (n_11));
  CLKXOR2X1 g125__3680(.A (P[0]), .B (n_34), .Y (S[0]));
  NAND2XL g127__2802(.A (P[2]), .B (P[1]), .Y (n_9));
  NAND2X1 g128__1705(.A (Cin), .B (P[0]), .Y (n_8));
  OAI21X2 g74__5122(.A0 (n_1), .A1 (n_6), .B0 (n_17), .Y (GG));
  NOR3X2 g75__8246(.A (G[2]), .B (n_0), .C (n_46), .Y (n_6));
  NAND2X2 g83__7482(.A (P[0]), .B (P[1]), .Y (n_2));
  CLKINVX1 g84(.A (P[3]), .Y (n_1));
  AND2X1 g2__4733(.A (G[1]), .B (P[2]), .Y (n_0));
  CLKBUFX2 fopt(.A (Cin), .Y (n_34));
  INVX1 fopt130(.A (n_37), .Y (n_36));
  INVX1 fopt1(.A (n_12), .Y (n_37));
  NOR2X2 g78__133(.A (n_43), .B (n_2), .Y (GP));
  NAND2X2 g80__134(.A (P[3]), .B (P[2]), .Y (n_43));
  NOR2XL g2(.A (n_0), .B (n_46), .Y (n_45));
  AND3X1 g135(.A (G[0]), .B (P[2]), .C (P[1]), .Y (n_46));
endmodule

module CLA16_5(A, B, Cin, S, GG, GP);
  input [15:0] A, B;
  input Cin;
  output [15:0] S;
  output GG, GP;
  wire [15:0] A, B;
  wire Cin;
  wire [15:0] S;
  wire GG, GP;
  wire [3:0] GG4;
  wire [3:0] GP4;
  wire c8, c12, n_3, n_5, n_6, n_11, n_12, n_13;
  wire n_14, n_15, n_67, n_69, n_71, n_73, n_75, n_76;
  wire n_77, n_79, n_80, n_83, n_86, n_87, n_88;
  CLA4_23 grp0(.A (A[3:0]), .B (B[3:0]), .Cin (Cin), .S (S[3:0]), .GG
       (GG4[0]), .GP (GP4[0]));
  CLA4_22 grp1(.A (A[7:4]), .B (B[7:4]), .Cin (n_71), .S (S[7:4]), .GG
       (GG4[1]), .GP (GP4[1]));
  CLA4_21 grp2(.A (A[11:8]), .B (B[11:8]), .Cin (c8), .S (S[11:8]), .GG
       (GG4[2]), .GP (GP4[2]));
  CLA4_20 grp3(.A (A[15:12]), .B (B[15:12]), .Cin (c12), .S (S[15:12]),
       .GG (GG4[3]), .GP (GP4[3]));
  NAND2X2 g36__6161(.A (n_14), .B (n_15), .Y (GG));
  AOI21X2 g37__9315(.A0 (n_11), .A1 (GG4[1]), .B0 (n_13), .Y (n_15));
  AOI21X2 g38__9945(.A0 (n_83), .A1 (GG4[2]), .B0 (GG4[3]), .Y (n_14));
  NOR2X2 g39__2883(.A (n_87), .B (n_12), .Y (GP));
  NOR3X1 g40__2346(.A (n_87), .B (n_79), .C (n_75), .Y (n_13));
  NAND2X2 g41__1666(.A (GP4[1]), .B (GP4[0]), .Y (n_12));
  CLKINVX1 g43(.A (n_87), .Y (n_11));
  OAI21X2 g50__5477(.A0 (n_79), .A1 (n_5), .B0 (n_76), .Y (c8));
  NAND3X2 g49__2398(.A (n_6), .B (n_3), .C (n_86), .Y (c12));
  AOI31XL g51__5107(.A0 (n_73), .A1 (GP4[2]), .A2 (n_80), .B0 (GG4[2]),
       .Y (n_6));
  AOI21X4 g53__6260(.A0 (n_67), .A1 (Cin), .B0 (n_73), .Y (n_5));
  NAND2XL g55__8428(.A (GP4[2]), .B (n_77), .Y (n_3));
  INVX1 fopt(.A (n_69), .Y (n_67));
  INVX1 fopt2(.A (GP4[0]), .Y (n_69));
  CLKINVX1 fopt59(.A (n_5), .Y (n_71));
  INVX1 fopt61(.A (n_75), .Y (n_73));
  INVX1 fopt62(.A (GG4[0]), .Y (n_75));
  INVX1 fopt63(.A (n_77), .Y (n_76));
  CLKBUFX2 fopt64(.A (GG4[1]), .Y (n_77));
  CLKINVX1 fopt66(.A (n_79), .Y (n_80));
  CLKINVX2 fopt67(.A (GP4[1]), .Y (n_79));
  BUFX2 fopt68(.A (GP4[3]), .Y (n_83));
  NAND2BX2 g8(.AN (n_88), .B (Cin), .Y (n_86));
  NAND2X2 g48__69(.A (GP4[3]), .B (GP4[2]), .Y (n_87));
  NAND3X1 g2(.A (GP4[2]), .B (n_80), .C (GP4[0]), .Y (n_88));
endmodule

module initialize_79(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_78(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_77(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_76(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module CLA4_19(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_24, t_p2p1g0;
  initialize_79 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_78 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_77 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_76 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  NAND2BX1 g73__4733(.AN (G[3]), .B (n_7), .Y (GG));
  OAI21X1 g74__6161(.A0 (G[2]), .A1 (n_6), .B0 (P[3]), .Y (n_7));
  NAND2XL g75__9315(.A (n_8), .B (t_p2p1g0), .Y (n_6));
  NAND3X1 g76__9945(.A (G[0]), .B (P[2]), .C (P[1]), .Y (t_p2p1g0));
  AND4XL g77__2883(.A (P[2]), .B (P[3]), .C (P[1]), .D (P[0]), .Y (GP));
  NAND2XL g78__2346(.A (P[2]), .B (G[1]), .Y (n_8));
  OAI21X1 g117__1666(.A0 (P[2]), .A1 (n_4), .B0 (n_5), .Y (S[2]));
  NAND2XL g118__7410(.A (P[2]), .B (n_4), .Y (n_5));
  AOI21X1 g119__6417(.A0 (P[1]), .A1 (n_2), .B0 (G[1]), .Y (n_4));
  CLKXOR2X1 g120__5477(.A (P[3]), .B (n_3), .Y (S[3]));
  MXI2XL g121__2398(.A (n_1), .B (n_2), .S0 (P[1]), .Y (S[1]));
  NAND4BXL g122__5107(.AN (G[2]), .B (n_8), .C (t_p2p1g0), .D (n_0), .Y
       (n_3));
  CLKINVX1 g123(.A (n_1), .Y (n_2));
  AOI21XL g124__6260(.A0 (Cin), .A1 (P[0]), .B0 (G[0]), .Y (n_1));
  NAND4XL g125__4319(.A (Cin), .B (P[1]), .C (P[2]), .D (P[0]), .Y
       (n_0));
  CLKXOR2X1 g126__8428(.A (P[0]), .B (n_24), .Y (S[0]));
  CLKBUFX2 fopt(.A (Cin), .Y (n_24));
endmodule

module initialize_75(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_74(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_73(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g2(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_72(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g28__6131(.A (x), .B (y), .CO (g), .S (p));
endmodule

module CLA4_18(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_9, n_10;
  wire n_11, n_12, n_28, t_p2p1g0;
  initialize_75 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_74 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_73 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_72 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  OAI21X1 g116__1881(.A0 (P[2]), .A1 (n_10), .B0 (n_11), .Y (S[2]));
  NAND2X1 g117__5115(.A (n_10), .B (P[2]), .Y (n_11));
  AOI21X2 g118__7482(.A0 (P[1]), .A1 (n_7), .B0 (G[1]), .Y (n_10));
  CLKXOR2X1 g119__4733(.A (P[3]), .B (n_9), .Y (S[3]));
  NAND3BX1 g121__9315(.AN (G[2]), .B (n_5), .C (n_6), .Y (n_9));
  NAND2BX2 g123__9945(.AN (G[0]), .B (n_3), .Y (n_7));
  NAND3BX1 g124__2883(.AN (n_4), .B (P[0]), .C (Cin), .Y (n_6));
  CLKXOR2X1 g125__2346(.A (P[0]), .B (n_28), .Y (S[0]));
  AND2XL g126__1666(.A (n_12), .B (t_p2p1g0), .Y (n_5));
  NAND2XL g127__7410(.A (P[2]), .B (P[1]), .Y (n_4));
  NAND2X2 g128__6417(.A (P[0]), .B (Cin), .Y (n_3));
  AO21X1 g74__5477(.A0 (P[3]), .A1 (n_2), .B0 (G[3]), .Y (GG));
  NAND3BXL g75__2398(.AN (G[2]), .B (n_12), .C (t_p2p1g0), .Y (n_2));
  NAND3X1 g76__5107(.A (G[0]), .B (P[2]), .C (P[1]), .Y (t_p2p1g0));
  NAND2XL g78__4319(.A (P[2]), .B (G[1]), .Y (n_12));
  CLKBUFX2 fopt(.A (Cin), .Y (n_28));
  AND4XL g2(.A (P[3]), .B (P[1]), .C (P[0]), .D (P[2]), .Y (GP));
  CLKXOR2X1 g129(.A (n_7), .B (P[1]), .Y (S[1]));
endmodule

module initialize_71(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3;
  NAND2X1 g31__3680(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OA21X2 g34(.A0 (y), .A1 (x), .B0 (n_3), .Y (p));
endmodule

module initialize_70(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  wire n_3, n_8;
  AND2X6 g29__1617(.A (n_3), .B (n_8), .Y (p));
  NAND2X1 g31__1705(.A (x), .B (y), .Y (n_3));
  CLKINVX1 fopt(.A (n_3), .Y (g));
  OR2XL g2(.A (y), .B (x), .Y (n_8));
endmodule

module initialize_69(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g28__5122(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_68(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g28__8246(.A (x), .B (y), .CO (g), .S (p));
endmodule

module CLA4_17(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_10, n_12;
  wire n_13, n_29, n_36, n_45, n_46, n_47, n_48, t_p2p1g0;
  initialize_71 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_70 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_69 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_68 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  OAI21X1 g116__7098(.A0 (P[2]), .A1 (n_36), .B0 (n_12), .Y (S[2]));
  NAND2X1 g117__6131(.A (n_36), .B (P[2]), .Y (n_12));
  MXI2X1 g119__5115(.A (n_2), .B (P[3]), .S0 (n_10), .Y (S[3]));
  NAND3BX2 g121__4733(.AN (G[2]), .B (n_5), .C (n_6), .Y (n_10));
  NAND3BX2 g125__9945(.AN (n_4), .B (P[0]), .C (Cin), .Y (n_6));
  CLKXOR2X1 g126__2883(.A (P[0]), .B (n_29), .Y (S[0]));
  AND2X1 g127__2346(.A (n_13), .B (t_p2p1g0), .Y (n_5));
  NAND2XL g128__1666(.A (P[2]), .B (P[1]), .Y (n_4));
  INVX1 g130(.A (P[3]), .Y (n_2));
  NAND2BX1 g74__6417(.AN (G[3]), .B (n_1), .Y (GG));
  OAI21X1 g75__5477(.A0 (G[2]), .A1 (n_0), .B0 (P[3]), .Y (n_1));
  NAND2XL g76__2398(.A (n_13), .B (t_p2p1g0), .Y (n_0));
  NAND3XL g77__5107(.A (G[0]), .B (P[2]), .C (P[1]), .Y (t_p2p1g0));
  AND4X1 g78__6260(.A (P[2]), .B (P[3]), .C (P[1]), .D (P[0]), .Y (GP));
  NAND2XL g79__4319(.A (P[2]), .B (G[1]), .Y (n_13));
  CLKBUFX2 fopt(.A (Cin), .Y (n_29));
  AOI21X2 g118__132(.A0 (P[1]), .A1 (n_48), .B0 (G[1]), .Y (n_36));
  AOI21XL g4(.A0 (P[0]), .A1 (Cin), .B0 (G[0]), .Y (n_45));
  NAND2X2 g143(.A (n_46), .B (n_47), .Y (n_48));
  CLKINVX1 g144(.A (G[0]), .Y (n_46));
  NAND2X2 g129__145(.A (P[0]), .B (Cin), .Y (n_47));
  XNOR2X1 g2(.A (P[1]), .B (n_45), .Y (S[1]));
endmodule

module initialize_67(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g28__8428(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_66(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g28__5526(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_65(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g28__6783(.A (x), .B (y), .CO (g), .S (p));
endmodule

module initialize_64(x, y, g, p);
  input x, y;
  output g, p;
  wire x, y;
  wire g, p;
  ADDHX1 g28__3680(.A (x), .B (y), .CO (g), .S (p));
endmodule

module CLA4_16(A, B, Cin, S, GG, GP);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output GG, GP;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire GG, GP;
  wire [3:0] G;
  wire [3:0] P;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_10;
  wire n_12, n_13, n_29, n_32, n_33, n_34, n_35, n_36;
  wire t_p2p1g0;
  initialize_67 ini0(.x (A[0]), .y (B[0]), .g (G[0]), .p (P[0]));
  initialize_66 ini1(.x (A[1]), .y (B[1]), .g (G[1]), .p (P[1]));
  initialize_65 ini2(.x (A[2]), .y (B[2]), .g (G[2]), .p (P[2]));
  initialize_64 ini3(.x (A[3]), .y (B[3]), .g (G[3]), .p (P[3]));
  OAI21X1 g116__1617(.A0 (P[2]), .A1 (n_35), .B0 (n_12), .Y (S[2]));
  NAND2X1 g117__2802(.A (n_35), .B (P[2]), .Y (n_12));
  MXI2X1 g119__5122(.A (n_3), .B (P[3]), .S0 (n_10), .Y (S[3]));
  MXI2X1 g120__8246(.A (n_36), .B (n_29), .S0 (P[1]), .Y (S[1]));
  NAND3BX2 g121__7098(.AN (G[2]), .B (n_6), .C (n_7), .Y (n_10));
  NAND3BX1 g124__1881(.AN (n_5), .B (P[0]), .C (Cin), .Y (n_7));
  CLKXOR2X1 g125__5115(.A (P[0]), .B (n_2), .Y (S[0]));
  AND2X1 g126__7482(.A (n_13), .B (t_p2p1g0), .Y (n_6));
  NAND2XL g127__4733(.A (P[2]), .B (P[1]), .Y (n_5));
  INVX1 g129(.A (P[3]), .Y (n_3));
  CLKBUFX2 fopt(.A (Cin), .Y (n_2));
  NAND2BX1 g74__9315(.AN (G[3]), .B (n_1), .Y (GG));
  OAI21X1 g75__9945(.A0 (G[2]), .A1 (n_0), .B0 (P[3]), .Y (n_1));
  NAND2XL g76__2883(.A (n_13), .B (t_p2p1g0), .Y (n_0));
  NAND3X1 g77__2346(.A (G[0]), .B (P[2]), .C (P[1]), .Y (t_p2p1g0));
  AND4X1 g78__1666(.A (P[2]), .B (P[3]), .C (P[1]), .D (P[0]), .Y (GP));
  NAND2XL g79__7410(.A (P[2]), .B (G[1]), .Y (n_13));
  INVX1 fopt130(.A (n_36), .Y (n_29));
  AOI21X2 g118__131(.A0 (P[1]), .A1 (n_34), .B0 (G[1]), .Y (n_35));
  NAND2X2 g1(.A (n_32), .B (n_33), .Y (n_34));
  CLKINVX1 g2(.A (G[0]), .Y (n_32));
  NAND2X2 g128__132(.A (P[0]), .B (Cin), .Y (n_33));
  INVX1 fopt133(.A (n_34), .Y (n_36));
endmodule

module CLA16_4(A, B, Cin, S, GG, GP);
  input [15:0] A, B;
  input Cin;
  output [15:0] S;
  output GG, GP;
  wire [15:0] A, B;
  wire Cin;
  wire [15:0] S;
  wire GG, GP;
  wire [3:0] GG4;
  wire [3:0] GP4;
  wire c8, c12, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_62;
  CLA4_19 grp0(.A (A[3:0]), .B (B[3:0]), .Cin (Cin), .S (S[3:0]), .GG
       (GG4[0]), .GP (GP4[0]));
  CLA4_18 grp1(.A (A[7:4]), .B (B[7:4]), .Cin (n_62), .S (S[7:4]), .GG
       (GG4[1]), .GP (GP4[1]));
  CLA4_17 grp2(.A (A[11:8]), .B (B[11:8]), .Cin (c8), .S (S[11:8]), .GG
       (GG4[2]), .GP (GP4[2]));
  CLA4_16 grp3(.A (A[15:12]), .B (B[15:12]), .Cin (c12), .S (S[15:12]),
       .GG (GG4[3]), .GP (GP4[3]));
  NAND3X1 g35__6417(.A (n_9), .B (n_7), .C (n_8), .Y (GG));
  AOI31X1 g36__5477(.A0 (GG4[1]), .A1 (GP4[3]), .A2 (GP4[2]), .B0
       (GG4[3]), .Y (n_9));
  AND4X1 g37__2398(.A (GP4[3]), .B (GP4[2]), .C (GP4[1]), .D (GP4[0]),
       .Y (GP));
  NAND4XL g38__5107(.A (GP4[3]), .B (GP4[2]), .C (GP4[1]), .D (GG4[0]),
       .Y (n_8));
  NAND2XL g39__6260(.A (GP4[3]), .B (GG4[2]), .Y (n_7));
  OAI21X4 g48__4319(.A0 (n_0), .A1 (n_5), .B0 (n_1), .Y (c8));
  NAND3X4 g49__8428(.A (n_6), .B (n_3), .C (n_4), .Y (c12));
  AOI31X1 g50__5526(.A0 (GG4[0]), .A1 (GP4[2]), .A2 (GP4[1]), .B0
       (GG4[2]), .Y (n_6));
  AOI21X4 g52__6783(.A0 (GP4[0]), .A1 (Cin), .B0 (GG4[0]), .Y (n_5));
  NAND3BX4 g53__3680(.AN (n_2), .B (GP4[0]), .C (Cin), .Y (n_4));
  NAND2XL g54__1617(.A (GP4[2]), .B (GG4[1]), .Y (n_3));
  NAND2XL g55__2802(.A (GP4[2]), .B (GP4[1]), .Y (n_2));
  CLKINVX1 g56(.A (GG4[1]), .Y (n_1));
  CLKINVX1 g57(.A (GP4[1]), .Y (n_0));
  CLKINVX2 fopt(.A (n_5), .Y (n_62));
endmodule

module CLA64(clk, A, B, Cin, S, GG, GP);
  input clk, Cin;
  input [63:0] A, B;
  output [63:0] S;
  output GG, GP;
  wire clk, Cin;
  wire [63:0] A, B;
  wire [63:0] S;
  wire GG, GP;
  wire [3:0] GG16;
  wire [3:0] GP16;
  wire c16, c32, n_0, n_1, n_2, n_3, n_4, n_11;
  wire n_14, n_16, n_212, n_213, n_215, n_217, n_218, n_219;
  wire n_224, n_225, n_226, n_227, n_228;
  CLA16 blk0(A[15:0], B[15:0], Cin, S[15:0], GG16[0], GP16[0]);
  CLA16_6 blk1(A[31:16], B[31:16], c16, S[31:16], GG16[1], GP16[1]);
  CLA16_5 blk2(A[47:32], B[47:32], c32, S[47:32], GG16[2], GP16[2]);
  CLA16_4 blk3(A[63:48], B[63:48], n_225, S[63:48], GG16[3], GP16[3]);
  INVXL g18(.A (GG16[3]), .Y (n_16));
  OAI21X4 g69__5122(.A0 (n_213), .A1 (n_14), .B0 (n_4), .Y (c32));
  OAI211X1 g70__8246(.A0 (n_3), .A1 (n_0), .B0 (n_16), .C0 (n_11), .Y
       (GG));
  CLKINVX3 g72(.A (n_14), .Y (c16));
  NOR2X4 g73__6131(.A (n_226), .B (GG16[0]), .Y (n_14));
  AND4X1 g76__7482(.A (GP16[3]), .B (n_2), .C (n_212), .D (GP16[0]), .Y
       (GP));
  NAND4XL g77__4733(.A (GG16[0]), .B (n_2), .C (n_212), .D (GP16[3]),
       .Y (n_11));
  CLKINVX1 g84(.A (GG16[1]), .Y (n_4));
  INVX1 g85(.A (GP16[3]), .Y (n_3));
  CLKINVX2 g86(.A (n_1), .Y (n_2));
  CLKINVX1 g87(.A (GP16[2]), .Y (n_1));
  DLY2X1 fopt(.A (n_219), .Y (n_0));
  CLKINVX1 fopt1(.A (n_212), .Y (n_213));
  CLKINVX1 fopt2(.A (n_215), .Y (n_212));
  CLKINVX1 fopt3(.A (GP16[1]), .Y (n_215));
  CLKINVX2 g2(.A (n_217), .Y (n_218));
  NOR3X2 g71__101(.A (n_215), .B (n_1), .C (n_227), .Y (n_217));
  AOI21X4 g74__102(.A0 (n_2), .A1 (GG16[1]), .B0 (GG16[2]), .Y (n_219));
  NAND3X4 g105(.A (n_218), .B (n_219), .C (n_224), .Y (n_225));
  NAND2X2 g106(.A (n_228), .B (GG16[0]), .Y (n_224));
  CLKAND2X2 g109(.A (Cin), .B (GP16[0]), .Y (n_226));
  NAND2X2 g80__110(.A (Cin), .B (GP16[0]), .Y (n_227));
  AND2X1 g111(.A (GP16[1]), .B (GP16[2]), .Y (n_228));
endmodule

