
//input ports
add mapped point A[63] A[63] -type PI PI
add mapped point A[62] A[62] -type PI PI
add mapped point A[61] A[61] -type PI PI
add mapped point A[60] A[60] -type PI PI
add mapped point A[59] A[59] -type PI PI
add mapped point A[58] A[58] -type PI PI
add mapped point A[57] A[57] -type PI PI
add mapped point A[56] A[56] -type PI PI
add mapped point A[55] A[55] -type PI PI
add mapped point A[54] A[54] -type PI PI
add mapped point A[53] A[53] -type PI PI
add mapped point A[52] A[52] -type PI PI
add mapped point A[51] A[51] -type PI PI
add mapped point A[50] A[50] -type PI PI
add mapped point A[49] A[49] -type PI PI
add mapped point A[48] A[48] -type PI PI
add mapped point A[47] A[47] -type PI PI
add mapped point A[46] A[46] -type PI PI
add mapped point A[45] A[45] -type PI PI
add mapped point A[44] A[44] -type PI PI
add mapped point A[43] A[43] -type PI PI
add mapped point A[42] A[42] -type PI PI
add mapped point A[41] A[41] -type PI PI
add mapped point A[40] A[40] -type PI PI
add mapped point A[39] A[39] -type PI PI
add mapped point A[38] A[38] -type PI PI
add mapped point A[37] A[37] -type PI PI
add mapped point A[36] A[36] -type PI PI
add mapped point A[35] A[35] -type PI PI
add mapped point A[34] A[34] -type PI PI
add mapped point A[33] A[33] -type PI PI
add mapped point A[32] A[32] -type PI PI
add mapped point A[31] A[31] -type PI PI
add mapped point A[30] A[30] -type PI PI
add mapped point A[29] A[29] -type PI PI
add mapped point A[28] A[28] -type PI PI
add mapped point A[27] A[27] -type PI PI
add mapped point A[26] A[26] -type PI PI
add mapped point A[25] A[25] -type PI PI
add mapped point A[24] A[24] -type PI PI
add mapped point A[23] A[23] -type PI PI
add mapped point A[22] A[22] -type PI PI
add mapped point A[21] A[21] -type PI PI
add mapped point A[20] A[20] -type PI PI
add mapped point A[19] A[19] -type PI PI
add mapped point A[18] A[18] -type PI PI
add mapped point A[17] A[17] -type PI PI
add mapped point A[16] A[16] -type PI PI
add mapped point A[15] A[15] -type PI PI
add mapped point A[14] A[14] -type PI PI
add mapped point A[13] A[13] -type PI PI
add mapped point A[12] A[12] -type PI PI
add mapped point A[11] A[11] -type PI PI
add mapped point A[10] A[10] -type PI PI
add mapped point A[9] A[9] -type PI PI
add mapped point A[8] A[8] -type PI PI
add mapped point A[7] A[7] -type PI PI
add mapped point A[6] A[6] -type PI PI
add mapped point A[5] A[5] -type PI PI
add mapped point A[4] A[4] -type PI PI
add mapped point A[3] A[3] -type PI PI
add mapped point A[2] A[2] -type PI PI
add mapped point A[1] A[1] -type PI PI
add mapped point A[0] A[0] -type PI PI
add mapped point B[63] B[63] -type PI PI
add mapped point B[62] B[62] -type PI PI
add mapped point B[61] B[61] -type PI PI
add mapped point B[60] B[60] -type PI PI
add mapped point B[59] B[59] -type PI PI
add mapped point B[58] B[58] -type PI PI
add mapped point B[57] B[57] -type PI PI
add mapped point B[56] B[56] -type PI PI
add mapped point B[55] B[55] -type PI PI
add mapped point B[54] B[54] -type PI PI
add mapped point B[53] B[53] -type PI PI
add mapped point B[52] B[52] -type PI PI
add mapped point B[51] B[51] -type PI PI
add mapped point B[50] B[50] -type PI PI
add mapped point B[49] B[49] -type PI PI
add mapped point B[48] B[48] -type PI PI
add mapped point B[47] B[47] -type PI PI
add mapped point B[46] B[46] -type PI PI
add mapped point B[45] B[45] -type PI PI
add mapped point B[44] B[44] -type PI PI
add mapped point B[43] B[43] -type PI PI
add mapped point B[42] B[42] -type PI PI
add mapped point B[41] B[41] -type PI PI
add mapped point B[40] B[40] -type PI PI
add mapped point B[39] B[39] -type PI PI
add mapped point B[38] B[38] -type PI PI
add mapped point B[37] B[37] -type PI PI
add mapped point B[36] B[36] -type PI PI
add mapped point B[35] B[35] -type PI PI
add mapped point B[34] B[34] -type PI PI
add mapped point B[33] B[33] -type PI PI
add mapped point B[32] B[32] -type PI PI
add mapped point B[31] B[31] -type PI PI
add mapped point B[30] B[30] -type PI PI
add mapped point B[29] B[29] -type PI PI
add mapped point B[28] B[28] -type PI PI
add mapped point B[27] B[27] -type PI PI
add mapped point B[26] B[26] -type PI PI
add mapped point B[25] B[25] -type PI PI
add mapped point B[24] B[24] -type PI PI
add mapped point B[23] B[23] -type PI PI
add mapped point B[22] B[22] -type PI PI
add mapped point B[21] B[21] -type PI PI
add mapped point B[20] B[20] -type PI PI
add mapped point B[19] B[19] -type PI PI
add mapped point B[18] B[18] -type PI PI
add mapped point B[17] B[17] -type PI PI
add mapped point B[16] B[16] -type PI PI
add mapped point B[15] B[15] -type PI PI
add mapped point B[14] B[14] -type PI PI
add mapped point B[13] B[13] -type PI PI
add mapped point B[12] B[12] -type PI PI
add mapped point B[11] B[11] -type PI PI
add mapped point B[10] B[10] -type PI PI
add mapped point B[9] B[9] -type PI PI
add mapped point B[8] B[8] -type PI PI
add mapped point B[7] B[7] -type PI PI
add mapped point B[6] B[6] -type PI PI
add mapped point B[5] B[5] -type PI PI
add mapped point B[4] B[4] -type PI PI
add mapped point B[3] B[3] -type PI PI
add mapped point B[2] B[2] -type PI PI
add mapped point B[1] B[1] -type PI PI
add mapped point B[0] B[0] -type PI PI
add mapped point cin cin -type PI PI

//output ports
add mapped point sum[63] sum[63] -type PO PO
add mapped point sum[62] sum[62] -type PO PO
add mapped point sum[61] sum[61] -type PO PO
add mapped point sum[60] sum[60] -type PO PO
add mapped point sum[59] sum[59] -type PO PO
add mapped point sum[58] sum[58] -type PO PO
add mapped point sum[57] sum[57] -type PO PO
add mapped point sum[56] sum[56] -type PO PO
add mapped point sum[55] sum[55] -type PO PO
add mapped point sum[54] sum[54] -type PO PO
add mapped point sum[53] sum[53] -type PO PO
add mapped point sum[52] sum[52] -type PO PO
add mapped point sum[51] sum[51] -type PO PO
add mapped point sum[50] sum[50] -type PO PO
add mapped point sum[49] sum[49] -type PO PO
add mapped point sum[48] sum[48] -type PO PO
add mapped point sum[47] sum[47] -type PO PO
add mapped point sum[46] sum[46] -type PO PO
add mapped point sum[45] sum[45] -type PO PO
add mapped point sum[44] sum[44] -type PO PO
add mapped point sum[43] sum[43] -type PO PO
add mapped point sum[42] sum[42] -type PO PO
add mapped point sum[41] sum[41] -type PO PO
add mapped point sum[40] sum[40] -type PO PO
add mapped point sum[39] sum[39] -type PO PO
add mapped point sum[38] sum[38] -type PO PO
add mapped point sum[37] sum[37] -type PO PO
add mapped point sum[36] sum[36] -type PO PO
add mapped point sum[35] sum[35] -type PO PO
add mapped point sum[34] sum[34] -type PO PO
add mapped point sum[33] sum[33] -type PO PO
add mapped point sum[32] sum[32] -type PO PO
add mapped point sum[31] sum[31] -type PO PO
add mapped point sum[30] sum[30] -type PO PO
add mapped point sum[29] sum[29] -type PO PO
add mapped point sum[28] sum[28] -type PO PO
add mapped point sum[27] sum[27] -type PO PO
add mapped point sum[26] sum[26] -type PO PO
add mapped point sum[25] sum[25] -type PO PO
add mapped point sum[24] sum[24] -type PO PO
add mapped point sum[23] sum[23] -type PO PO
add mapped point sum[22] sum[22] -type PO PO
add mapped point sum[21] sum[21] -type PO PO
add mapped point sum[20] sum[20] -type PO PO
add mapped point sum[19] sum[19] -type PO PO
add mapped point sum[18] sum[18] -type PO PO
add mapped point sum[17] sum[17] -type PO PO
add mapped point sum[16] sum[16] -type PO PO
add mapped point sum[15] sum[15] -type PO PO
add mapped point sum[14] sum[14] -type PO PO
add mapped point sum[13] sum[13] -type PO PO
add mapped point sum[12] sum[12] -type PO PO
add mapped point sum[11] sum[11] -type PO PO
add mapped point sum[10] sum[10] -type PO PO
add mapped point sum[9] sum[9] -type PO PO
add mapped point sum[8] sum[8] -type PO PO
add mapped point sum[7] sum[7] -type PO PO
add mapped point sum[6] sum[6] -type PO PO
add mapped point sum[5] sum[5] -type PO PO
add mapped point sum[4] sum[4] -type PO PO
add mapped point sum[3] sum[3] -type PO PO
add mapped point sum[2] sum[2] -type PO PO
add mapped point sum[1] sum[1] -type PO PO
add mapped point sum[0] sum[0] -type PO PO
add mapped point cout cout -type PO PO

//inout ports




//Sequential Pins



//Black Boxes



//Empty Modules as Blackboxes
